const f=(code:string)=>`HS-FUNC-${code}-001`;
const set='HS-SET-CONCEPT-001',coord='MS-GEO-COORD-001';
const base=[set,f('MAPPING'),f('CONCEPT')];
/** Independent expected closures, not generated by the traversal under test. */
export const unlockScenarios=[
 {kind:'ordinary',target:f('DOMAIN'),expected:[...base,f('DOMAIN')]},
 {kind:'ordinary',target:f('RANGE'),expected:[...base,f('RANGE')]},
 {kind:'ordinary',target:f('PIECE'),expected:[...base,f('ANALYTIC'),f('PIECEDEF'),f('VALUE'),f('PIECE')]},
 {kind:'ordinary',target:f('REPRESENT'),expected:[...base,f('ANALYTIC'),f('TABLE'),coord,f('GRAPH'),f('REPRESENT')]},
 {kind:'ordinary',target:f('BISECTION'),expected:[...base,f('VALUE'),coord,f('GRAPH'),f('ZERO'),f('ZEROEXIST'),f('BISECTION')]},
 {kind:'key',target:f('CONCEPT'),expected:base},
 {kind:'key',target:f('MONO'),expected:[...base,f('MONO')]},
 {kind:'key',target:f('PARITY'),expected:[...base,f('DOMAIN'),f('PARITY')]},
 {kind:'key',target:f('QUAD'),expected:[...base,coord,f('GRAPH'),f('QUAD')]},
 {kind:'key',target:f('APPLY'),expected:[...base,f('ANALYTIC'),f('DOMAIN'),f('APPLY')]},
] as const;
export const pathScenarios=[
 {source:set,target:f('BISECTION')},
 {source:coord,target:f('QUAD')},
 {source:f('MAPPING'),target:f('PARITY')},
 {source:'HS-ALG-INEQUALITY-001',target:f('MONOPROOF')},
 {source:f('CONCEPT'),target:f('APPLY')},
] as const;
