import {test,expect} from '@playwright/test';

test('knowledge homepage filters systems and opens independent system pages',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:'数学 · Knowledge World'})).toBeVisible();
 await expect(page.locator('.portal-card')).toHaveCount(9);
 await page.getByRole('button',{name:/已接入/}).click();
 await expect(page.locator('.portal-card')).toHaveCount(1);
 await page.getByRole('button',{name:/全部/}).click();
 await page.getByLabel('搜索知识体系').fill('三角函数');
 await expect(page.locator('.portal-card')).toHaveCount(1);
 await page.locator('.portal-card[href="/systems/trigonometry"]').click();
 await expect(page.getByTestId('curriculum-trigonometry-world')).toBeVisible();
 await expect(page.getByText(/28 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('集合与逻辑');
 await page.locator('.portal-card[href="/systems/sets-logic"]').click();
 await expect(page.getByTestId('curriculum-sets-logic-world')).toBeVisible();
 await expect(page.getByText(/34 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('数列');
 await page.locator('.portal-card[href="/systems/sequences"]').click();
 await expect(page.getByTestId('curriculum-sequences-world')).toBeVisible();
 await expect(page.getByText(/37 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('代数与不等式');
 await page.locator('.portal-card[href="/systems/algebra"]').click();
 await expect(page.getByTestId('curriculum-algebra-world')).toBeVisible();
 await expect(page.getByText(/30 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('平面向量');
 await page.locator('.portal-card[href="/systems/vectors"]').click();
 await expect(page.getByTestId('curriculum-vectors-world')).toBeVisible();
 await expect(page.getByText(/30 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('几何与空间向量');
 await page.locator('.portal-card[href="/systems/geometry"]').click();
 await expect(page.getByTestId('curriculum-geometry-world')).toBeVisible();
 await expect(page.getByText(/50 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('概率与统计');
 await page.locator('.portal-card[href="/systems/probability"]').click();
 await expect(page.getByTestId('curriculum-probability-world')).toBeVisible();
 await expect(page.getByText(/69 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.getByLabel('搜索知识体系').fill('导数');
 await page.locator('.portal-card[href="/systems/calculus"]').click();
 await expect(page.getByTestId('curriculum-calculus-world')).toBeVisible();
 await expect(page.getByText(/41 个候选知识节点/)).toBeVisible();
 await page.getByRole('link',{name:'← 返回知识总览'}).click();
 await page.getByLabel('搜索知识体系').fill('');
 await page.locator('a.portal-card.is-live').click();
 await expect(page.getByRole('heading',{name:'函数 · Function Knowledge World'})).toBeVisible();
});
