import {useEffect,useRef,useState} from 'react';
import {usePreferences,lineColors,type LineColor} from './preferences';
import {worldProgressStorageKey} from '../function-world-model';
import './settings.css';
const scopes=[['functions','函数'],['sets-logic','集合与逻辑'],['algebra','代数与不等式'],['trigonometry','三角函数'],['vectors','平面向量'],['sequences','数列'],['geometry','几何与空间关系'],['probability','概率与统计'],['calculus','导数']];
type Account={user:{username:string;id:string}|null;csrfToken:string|null};
async function accountRequest(path:string,body?:unknown,csrf?:string|null):Promise<Account>{
 const response=await fetch('/api/v1/auth/'+path,{credentials:'same-origin',signal:AbortSignal.timeout(10000),method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(csrf?{'X-CSRF-Token':csrf}:{})},...(body?{body:JSON.stringify(body)}:{})});
 let result;try{result=await response.json();}catch{throw new Error('账户服务暂时不可用，请稍后重试。');}
 if(!response.ok)throw new Error(result.message??'账户操作失败。');if(body)window.dispatchEvent(new Event('kw:account-change'));return result;
}
export default function Settings(){
 const prefs=usePreferences(),dialog=useRef<HTMLDialogElement>(null),previousFocus=useRef<HTMLElement|null>(null);
 const [open,setOpen]=useState(false),[panel,setPanel]=useState<'menu'|'colors'|'progress'|'account'>('menu');
 const [scope,setScope]=useState('geometry'),[confirm,setConfirm]=useState(false),[message,setMessage]=useState(''),[backup,setBackup]=useState<Record<string,string>|null>(null);
 const [account,setAccount]=useState<Account|null>(null),[busy,setBusy]=useState(false),[register,setRegister]=useState(false);
 useEffect(()=>{const show=()=>{previousFocus.current=document.activeElement as HTMLElement;setPanel('menu');setMessage('');setConfirm(false);setOpen(true);};window.addEventListener('kw:open-settings',show);return()=>window.removeEventListener('kw:open-settings',show);},[]);
 useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)'),refresh=()=>prefs.refreshSystemTheme();media.addEventListener('change',refresh);return()=>media.removeEventListener('change',refresh);},[prefs.refreshSystemTheme]);
 useEffect(()=>{document.documentElement.dataset.theme=prefs.resolvedTheme;document.documentElement.dataset.comfort=String(prefs.comfort);document.documentElement.style.colorScheme=prefs.resolvedTheme==='day'?'light':'dark';},[prefs.resolvedTheme,prefs.comfort]);
 useEffect(()=>{if(!open)return;const element=dialog.current!,scroll=document.body.style.overflow;element.showModal();document.body.style.overflow='hidden';return()=>{element.close();document.body.style.overflow=scroll;previousFocus.current?.focus();};},[open]);
 const close=()=>{setBackup(null);setOpen(false);};
 async function loadAccount(){setPanel('account');setBusy(true);setMessage('');try{setAccount(await accountRequest('me'));}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 async function authenticate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const data=new FormData(event.currentTarget);try{setAccount(await accountRequest(register?'register':'login',{username:data.get('username'),password:data.get('password')}));setRegister(false);setMessage('账户已登录。本机知识体系进度仍单独保存。');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}
 const progressKeys=()=>Object.keys(localStorage).filter(key=>scope==='ponder'?key.startsWith('kw:ponder:'):scope==='all'?key===worldProgressStorageKey||/^kw:curriculum:[a-z-]+:v1$/.test(key)||key.startsWith('kw:ponder:'):key===(scope==='functions'?worldProgressStorageKey:`kw:curriculum:${scope}:v1`));
 const reset=()=>{try{const saved=Object.fromEntries(progressKeys().map(key=>[key,localStorage.getItem(key)!]));setBackup(saved);for(const key of Object.keys(saved))localStorage.removeItem(key);window.dispatchEvent(new CustomEvent('kw:progress-reset',{detail:{keys:Object.keys(saved),operation:'reset'}}));setConfirm(false);setMessage('所选本机记录已重置，可在关闭设置前撤销。');}catch{setMessage('无法访问本机存储，重置未完成。');}};
 const undo=()=>{try{if(backup)for(const [key,value] of Object.entries(backup))localStorage.setItem(key,value);window.dispatchEvent(new CustomEvent('kw:progress-reset',{detail:{keys:Object.keys(backup??{}),operation:'restore'}}));setBackup(null);setMessage('已恢复本次重置前的记录。');}catch{setMessage('恢复失败，请检查本机存储权限。');}};
 const names:Record<LineColor,string>={cyan:'青色线条',gold:'金色线条',green:'绿色线条',muted:'辅助线条'};
 return <>{open&&<dialog className="kw-settings" ref={dialog} aria-labelledby="settings-title" onCancel={event=>{event.preventDefault();close();}} onClose={close}>
 <h1 id="settings-title">{panel==='menu'?'选项':panel==='colors'?'思索线条颜色':panel==='progress'?'节点与观看记录':'账户'}</h1>
 {panel==='menu'?<><div className="kw-options-top"><button onClick={()=>prefs.update({theme:prefs.theme==='night'?'day':prefs.theme==='day'?'auto':'night'})}>显示模式：{prefs.theme==='day'?'日间':prefs.theme==='night'?'夜间':'跟随本机'}</button><button onClick={()=>prefs.update({comfort:!prefs.comfort})}>舒适阅读：{prefs.comfort?'开启':'关闭'}</button></div><label className="kw-volume-control"><span>音量</span><output>{Math.round(prefs.volume*100)}%</output><input type="range" min="0" max="100" step="1" value={Math.round(prefs.volume*100)} aria-label="音量" aria-valuetext={`${Math.round(prefs.volume*100)}%`} style={{'--kw-volume-progress':`${Math.round(prefs.volume*100)}%`} as React.CSSProperties} onChange={event=>prefs.update({volume:Number(event.target.value)/100})}/></label><div className="kw-options-grid"><button onClick={()=>setPanel('colors')}>思索线条颜色…</button><button onClick={()=>void loadAccount()}>账户…</button><button onClick={()=>{setPanel('progress');setMessage('');}}>节点重置…</button><button onClick={()=>{setScope('ponder');setPanel('progress');setMessage('');}}>思索观看记录…</button></div><p className="kw-settings-note">设置即时生效并保存在此浏览器。舒适阅读会放大文字、增加行距，并放慢思索播放。</p></>:
 panel==='colors'?<section className="kw-settings-content"><p>设置线条主体颜色；各思索场景使用同一组颜色。恢复默认后，会自动选择适合当前背景的颜色。</p><div className="kw-color-grid">{(Object.keys(names) as LineColor[]).map(key=><label key={key}>{names[key]}<span className="kw-color-preview" style={{borderBottomColor:prefs.colors[key]??lineColors('solid',prefs)[key]}}/><input type="color" aria-label={names[key]} value={prefs.colors[key]??lineColors('solid',prefs)[key]} onChange={event=>prefs.update({colors:{...prefs.colors,[key]:event.target.value}})}/><output>{prefs.colors[key]??'自动'}</output></label>)}</div><button onClick={()=>prefs.update({colors:{}})}>恢复默认线条颜色</button></section>:
 panel==='progress'?<section className="kw-settings-content"><p>仅重置选定范围的本机记录，账户服务器中的进度不受此操作影响。</p><label>重置范围<select value={scope} onChange={event=>{setScope(event.target.value);setConfirm(false);setMessage('');}}>{scopes.map(([id,name])=><option key={id} value={id}>{name}节点进度</option>)}<option value="ponder">全部思索观看记录</option><option value="all">全部本机节点与观看记录</option></select></label>{confirm?<div className="kw-reset-confirm"><p>确认重置这个范围？已掌握节点或观看记录将被清除。</p><button onClick={reset}>确认重置所选记录</button><button onClick={()=>setConfirm(false)}>取消</button></div>:<button onClick={()=>setConfirm(true)}>重置所选记录…</button>}{backup&&<button onClick={undo}>撤销本次重置</button>}</section>:
 <section className="kw-settings-content"><p>知识体系页记录本机进度；账户用于服务器知识图谱中的登录与进度。</p>{busy?<p role="status">正在连接账户服务…</p>:account?.user?<><p>当前账户：{account.user.username}</p><a href="/">返回知识总览</a><a href="/legacy">旧版账户测试图谱</a><button onClick={async()=>{setBusy(true);try{await accountRequest('logout',{},account.csrfToken);setAccount({user:null,csrfToken:null});setMessage('已退出账户。');}catch(error){setMessage((error as Error).message);}finally{setBusy(false);}}}>退出登录</button></>:<form onSubmit={authenticate}><label>用户名<input name="username" autoComplete="username" required pattern="[A-Za-z0-9_]{3,32}" minLength={3} maxLength={32}/></label><label>密码<input name="password" type="password" autoComplete={register?'new-password':'current-password'} required minLength={12} maxLength={128}/></label><button type="submit">{register?'创建并登录':'登录'}</button><button type="button" onClick={()=>setRegister(!register)}>{register?'切换至登录':'创建账户'}</button><button type="button" onClick={()=>void loadAccount()}>重试账户连接</button></form>}</section>}
 {message&&<p className="kw-settings-message" role="status">{message}</p>}{prefs.storageError&&<p role="alert">设置已在当前页面生效，但本机存储不可用，关闭页面后可能丢失。</p>}
 <button className="kw-settings-done" onClick={panel==='menu'?close:()=>{setPanel('menu');setMessage('');setConfirm(false);}}>完成</button>
 </dialog>}</>;
}
