export interface CurriculumFormula {latex:string;conditions:string}
const f=(latex:string,conditions='按当前概念摘要及教材出处所述条件使用。'):CurriculumFormula=>({latex,conditions});

/** Formula blocks transcribed from the candidate concept summaries. */
export const curriculumFormulas:Readonly<Record<string,readonly CurriculumFormula[]>>={
 'HS-SET-MEMBERSHIP-001':[f('a\\in A\\quad\\text{或}\\quad a\\notin A')],
 'HS-SET-BUILDER-001':[f('\\{x\\in A\\mid P(x)\\}')],
 'HS-SET-SUBSET-001':[f('A\\subseteq B')],
 'HS-SET-PROPER-SUBSET-001':[f('A\\subsetneq B\\iff A\\subseteq B\\;\\land\\;A\\ne B')],
 'HS-SET-EMPTY-001':[f('\\varnothing\\subseteq A')],
 'HS-SET-INCLUSION-LAWS-001':[f('A\\subseteq A'),f('A\\subseteq B,\\;B\\subseteq C\\implies A\\subseteq C')],
 'HS-SET-UNION-001':[f('A\\cup B')],
 'HS-SET-INTERSECTION-001':[f('A\\cap B')],
 'HS-SET-COMPLEMENT-001':[f('\\complement_U A=U\\setminus A','补集依赖所选全集 U。')],
 'HS-SET-INCLUSION-EXCLUSION-001':[f('|A\\cup B|=|A|+|B|-|A\\cap B|','A、B 为有限集合。')],
 'HS-LOGIC-IMPLICATION-001':[f('p\\implies q')],
 'HS-LOGIC-SUFFICIENT-001':[f('p\\implies q','p 是 q 的充分条件。')],
 'HS-LOGIC-NECESSARY-001':[f('p\\implies q','q 是 p 的必要条件。')],
 'HS-LOGIC-BICONDITIONAL-001':[f('p\\iff q\\iff(p\\implies q)\\land(q\\implies p)')],
 'HS-LOGIC-UNIVERSAL-001':[f('\\forall x\\in M,\\;P(x)')],
 'HS-LOGIC-EXISTENTIAL-001':[f('\\exists x\\in M,\\;P(x)')],
 'HS-LOGIC-UNIVERSAL-NEGATION-001':[f('\\neg(\\forall x\\in M,\\;P(x))\\iff\\exists x\\in M,\\;\\neg P(x)')],
 'HS-LOGIC-EXISTENTIAL-NEGATION-001':[f('\\neg(\\exists x\\in M,\\;P(x))\\iff\\forall x\\in M,\\;\\neg P(x)')],
 'HS-REAL-ORDER-001':[f('a>b\\iff a-b>0'),f('a=b\\iff a-b=0'),f('a<b\\iff a-b<0')],
 'HS-INEQUALITY-ADD-001':[f('a>b\\implies a+c>b+c')],
 'HS-INEQUALITY-COMPOUND-001':[f('a>b,\\;c>d\\implies a+c>b+d')],
 'HS-INEQUALITY-SQUARE-001':[f('(a-b)^2\\geq0\\implies a^2+b^2\\geq2ab','a、b 为实数；等号当且仅当 a=b。')],
 'HS-BASIC-INEQUALITY-001':[f('\\frac{a+b}{2}\\geq\\sqrt{ab}','a>0、b>0；等号当且仅当 a=b。')],
 'HS-BASIC-INEQUALITY-MINIMUM-001':[f('x+y\\geq2\\sqrt{P}','x,y>0，xy=P；等号在 x=y=√P 取得。')],
 'HS-BASIC-INEQUALITY-MAXIMUM-001':[f('xy\\leq\\frac{S^2}{4}','x,y>0，x+y=S；等号在 x=y=S/2 取得。')],
 'HS-QUADRATIC-FUNCTION-001':[f('y=ax^2+bx+c','a≠0。')],
 'HS-QUADRATIC-EQUATION-DISCRIMINANT-001':[f('\\Delta=b^2-4ac','a≠0；判别式正、零、负分别对应两个、一重、零个实根。')],
 'HS-QUADRATIC-ZEROS-001':[f('ax^2+bx+c=0','a≠0；实根对应函数零点。')],
 'HS-QUADRATIC-INEQUALITY-NO-ROOT-001':[f('\\Delta<0','a≠0；二次式恒与 a 同号。')],
 'HS-QUADRATIC-INEQUALITY-DOUBLE-ROOT-001':[f('\\Delta=0','a≠0；顶点处取零。')],
 'HS-QUADRATIC-ROOT-BOUND-001':[f('\\Delta=b^2-4ac','结合二次项系数与判别式符号判断是否恒严格同号。')],
 'HS-INEQUALITY-RECIPROCAL-001':[f('a>b>0\\implies\\frac1a<\\frac1b')],
 'HS-TRIG-DEGREE-RADIAN-001':[f('180^\\circ=\\pi\\;\\mathrm{rad}')],
 'HS-TRIG-ARC-LENGTH-001':[f('l=r\\alpha','α 必须以弧度计。')],
 'HS-TRIG-TAN-001':[f('\\tan\\alpha=\\frac{\\sin\\alpha}{\\cos\\alpha}','cos α≠0。')],
 'HS-TRIG-QUOTIENT-IDENTITY-001':[f('\\tan\\alpha=\\frac{\\sin\\alpha}{\\cos\\alpha}','cos α≠0。')],
 'HS-TRIG-PYTHAGOREAN-IDENTITY-001':[f('\\sin^2\\alpha+\\cos^2\\alpha=1')],
 'HS-TRIG-SIN-GRAPH-001':[f('y=\\sin x')],
 'HS-TRIG-COS-GRAPH-001':[f('y=\\cos x')],
 'HS-TRIG-SINUSOIDAL-FAMILY-001':[f('y=A\\sin(\\omega x+\\varphi)','A>0，ω>0。')],
 'HS-SEQ-SUM-TO-TERM-001':[f('a_1=S_1,\\qquad a_n=S_n-S_{n-1}\\;(n\\geq2)')],
 'HS-AP-MEAN-001':[f('2A=a+b')],
 'HS-AP-TERM-001':[f('a_n=a_1+(n-1)d')],
 'HS-AP-SUM-001':[f('S_n=\\frac{n(a_1+a_n)}2'),f('S_n=na_1+\\frac{n(n-1)d}2')],
 'HS-GP-MEAN-001':[f('G^2=ab','实数范围内应检查符号与平方根条件。')],
 'HS-GP-TERM-001':[f('a_n=a_1q^{n-1}')],
 'HS-GP-SUM-001':[f('S_n=\\frac{a_1(1-q^n)}{1-q}','q≠1。')],
 'HS-GP-SUM-Q1-001':[f('S_n=na_1','q=1。')],
 'HS-GP-RECURRENCE-TRANSFORM-001':[f('x_{n+1}=rx_n+c,\\qquad k=\\frac{c}{1-r}'),f('x_{n+1}-k=r(x_n-k)','r≠1。')],
 'HS-INDUCTION-BASE-001':[f('P(n_0)')],
 'HS-INDUCTION-HYPOTHESIS-001':[f('P(k)\\implies P(k+1)')],
 'HS-INDUCTION-STEP-001':[f('P(k)\\implies P(k+1)','k≥n₀。')],
 'HS-INDUCTION-CONCLUSION-001':[f('P(n_0)\\;\\land\\;\\bigl(P(k)\\implies P(k+1)\\bigr)\\;\\implies\\;P(n)\\;(n\\geq n_0)')],
 'HS-VECTOR-SUBTRACTION-001':[f('\\mathbf a-\\mathbf b=\\mathbf a+(-\\mathbf b)')],
 'HS-VECTOR-COLLINEAR-THEOREM-001':[f('\\mathbf b=\\lambda\\mathbf a','a 为非零向量；λ 为实数。')],
 'HS-VECTOR-DOT-PRODUCT-001':[f('\\mathbf a\\cdot\\mathbf b=|\\mathbf a|\\,|\\mathbf b|\\cos\\theta')],
 'HS-VECTOR-COORDINATE-MAGNITUDE-001':[f('|\\mathbf a|=\\sqrt{x^2+y^2}','a=(x,y)。')],
 'HS-VECTOR-COORDINATE-DOT-001':[f('\\mathbf a\\cdot\\mathbf b=x_1x_2+y_1y_2','a=(x₁,y₁)，b=(x₂,y₂)。')],
 'HS-GEO-VOLUME-SPHERE-001':[f('S=4\\pi r^2'),f('V=\\frac{4}{3}\\pi r^3','r>0。')],
 'HS-GEO-LINE-EQUATION-POINT-SLOPE-001':[f('y-y_0=k(x-x_0)')],
 'HS-GEO-POINT-LINE-DISTANCE-001':[f('d=\\frac{|Ax_0+By_0+C|}{\\sqrt{A^2+B^2}}','A、B 不同时为零。')],
 'HS-GEO-CIRCLE-EQUATION-001':[f('(x-a)^2+(y-b)^2=r^2','r>0。')],
 'HS-GEO-CIRCLE-GENERAL-001':[f('x^2+y^2+Dx+Ey+F=0','表示实圆需满足 D²+E²−4F>0。')],
 'HS-GEO-ELLIPSE-PARAMETERS-001':[f('c^2=a^2-b^2,\\qquad e=\\frac ca','a>b>0，0<e<1。')],
 'HS-GEO-HYPERBOLA-ASYMPTOTE-001':[f('e=\\frac ca','e>1；渐近线还需结合标准方程确定。')],
 'HS-PROB-UNION-INTERSECTION-001':[f('A\\cup B,\\qquad A\\cap B')],
 'HS-PROB-ADDITION-001':[f('P(A\\cup B)=P(A)+P(B)-P(A\\cap B)')],
 'HS-PROB-CONDITIONAL-001':[f('P(A\\mid B)=\\frac{P(A\\cap B)}{P(B)}','P(B)>0。')],
 'HS-PROB-INDEPENDENCE-001':[f('P(A\\cap B)=P(A)P(B)','A、B 独立。')],
 'HS-PERMUTATION-NUMBER-001':[f('A_n^m=\\frac{n!}{(n-m)!}','0≤m≤n。')],
 'HS-COMBINATION-NUMBER-001':[f('C_n^m=\\frac{n!}{m!(n-m)!}','0≤m≤n。')],
 'HS-COMBINATION-SYMMETRY-001':[f('C_n^m=C_n^{n-m}')],
 'HS-BINOMIAL-COEFFICIENTS-001':[f('T_{k+1}=C_n^k a^{n-k}b^k')],
 'HS-BINOMIAL-THEOREM-001':[f('(a+b)^n=\\sum_{k=0}^n C_n^k a^{n-k}b^k')],
 'HS-RV-BINOMIAL-PROB-001':[f('P(X=k)=C_n^k p^k(1-p)^{n-k}','X 服从参数 n、p 的二项分布。')],
 'HS-RV-NORMAL-STANDARDIZE-001':[f('Z=\\frac{X-\\mu}{\\sigma}','X~N(μ,σ²)，σ>0。')],
 'HS-CALC-DIFFERENCE-QUOTIENT-001':[f('\\frac{f(x_0+h)-f(x_0)}h','h≠0。')],
 'HS-CALC-SQUARE-ROOT-RULE-001':[f('(\\sqrt x)\\prime=\\frac1{2\\sqrt x}','x>0。')],
 'HS-CALC-TANGENT-SLOPE-001':[f('k=f\\prime(x_0)','f 在 x₀ 处可导。')],
 'HS-CALC-TANGENT-EQUATION-001':[f('y-f(x_0)=f\\prime(x_0)(x-x_0)','f 在 x₀ 处可导。')],
 'HS-CALC-PRODUCT-RULE-001':[f('(uv)\\prime=u\\prime v+uv\\prime')],
 'HS-CALC-QUOTIENT-RULE-001':[f('\\left(\\frac uv\\right)\\prime=\\frac{u\\prime v-uv\\prime}{v^2}','v≠0。')],
 'HS-CALC-EXPONENTIAL-RULE-001':[f('\\frac{d}{dx}a^x=a^x\\ln a','a>0 且 a≠1。')],
 'HS-CALC-LOGARITHM-RULE-001':[f('\\frac{d}{dx}\\ln x=\\frac1x','x>0。')],
 'HS-CALC-TRIG-RULE-001':[f('\\frac{d}{dx}\\sin x=\\cos x'),f('\\frac{d}{dx}\\cos x=-\\sin x')],
 'HS-CALC-RECIPROCAL-RULE-001':[f('\\left(\\frac1x\\right)\\prime=-\\frac1{x^2}','x≠0。')],
 'HS-CALC-EXTREMA-NECESSARY-CONDITION-001':[f('f\\prime(x_0)=0','内点处可导且在 x₀ 取得极值时，这是必要条件。')],
 'HS-CALC-LOG-BASE-RULE-001':[f('\\frac{d}{dx}\\log_a x=\\frac1{x\\ln a}','a>0、a≠1、x>0。')],
};
