import {describe,it,expect,beforeAll,afterAll} from 'vitest';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {openDatabase,type Database} from '../../packages/database/src/connection';
import {setupDatabase} from '../../scripts/setup-db';
import {makeApp} from '../../apps/api/src/app';
import {nodeSpecs} from '../../content/fixtures/function-slice';
const origin='http://localhost:4173';
let db:Database,app:Awaited<ReturnType<typeof makeApp>>,directory:string;
const accounts:{cookie:string;csrf:string;username:string;id:string;password:string}[]=[];
const id=(i:number)=>nodeSpecs[i][0];
async function register(){const username='test_'+randomUUID().slice(0,8),password=randomUUID();const response=await app.inject({method:'POST',url:'/api/v1/auth/register',headers:{origin},payload:{username,password}});expect(response.statusCode).toBe(200);const body=response.json();const account={cookie:response.cookies[0].name+'='+response.cookies[0].value,csrf:body.csrfToken,username,id:body.user.id,password};accounts.push(account);return account;}
async function progress(a=accounts[0]){return (await app.inject({url:'/api/v1/me/progress',headers:{cookie:a.cookie}})).json();}
async function command(c:unknown,a=accounts[0],extra:Record<string,unknown>={}){const p=await progress(a);const payload={command:c,idempotencyKey:randomUUID(),graphReleaseId:p.graphReleaseId,expectedRevision:p.revision,...extra};return {response:await app.inject({method:'POST',url:'/api/v1/me/progress/commands',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload}),payload};}
describe('account and PostgreSQL-compatible persistent transactions',()=>{
 beforeAll(async()=>{directory=await mkdtemp(join(tmpdir(),'kw-phase1-'));db=await openDatabase(process.env.DATABASE_MODE==='postgres'?{mode:'postgres'}:{mode:'pglite',directory});await setupDatabase(db);app=await makeApp(db,{rateLimit:false});await register();await register();});
 afterAll(async()=>{await app?.close();await db?.close();if(directory)await rm(directory,{recursive:true,force:true});});
 it('executes the Phase 0 migration and exposes exactly 20 test nodes',async()=>{const graph=await app.inject({url:'/api/v1/knowledge/graph'});expect(graph.json().nodes).toHaveLength(20);const version=await db.query<{version:string}>('SELECT version()');console.log('Database engine:',version.rows[0].version.split(' on ')[0]);});
 it('blocks guest progress and CSRF / forged origin',async()=>{expect((await app.inject({url:'/api/v1/me/progress'})).statusCode).toBe(401);const a=accounts[0];expect((await app.inject({method:'POST',url:'/api/v1/me/progress/commands',headers:{cookie:a.cookie,origin},payload:{}})).statusCode).toBe(403);expect((await app.inject({method:'POST',url:'/api/v1/auth/login',headers:{origin:'https://attacker.invalid'},payload:{}})).statusCode).toBe(403);});
 it('does not return password hashes and ignores no role injection',async()=>{const me=await app.inject({url:'/api/v1/auth/me',headers:{cookie:accounts[0].cookie}});expect(me.body).not.toContain('password');expect((await app.inject({method:'POST',url:'/api/v1/auth/register',headers:{origin},payload:{username:'admin_injection',password:randomUUID(),role:'admin'}})).statusCode).toBe(422);});
 it('rejects unlocking a locked node with no progress',async()=>{expect((await command({kind:'unlock',nodeId:id(15)})).response.statusCode).toBe(422);expect((await progress()).unlocked).toHaveLength(0);});
 it('initializes strong ancestors atomically, not weak / sibling nodes',async()=>{const {response}=await command({kind:'initialize',targetNodeIds:[id(15)]});expect(response.statusCode).toBe(200);const ids=response.json().unlocked.map((n:any)=>n.nodeId);expect(ids).toContain(id(10));expect(ids).toContain(id(15));expect(ids).not.toContain(id(14));expect(ids).not.toContain(id(7));});
 it('stores progress per account, never globally',async()=>{expect((await progress(accounts[1])).unlocked).toHaveLength(0);expect((await progress()).unlocked.length).toBeGreaterThan(0);});
 it('finishes initialization and rejects later initialization',async()=>{expect((await command({kind:'finish_initialization'})).response.statusCode).toBe(200);expect((await command({kind:'initialize',targetNodeIds:[id(19)]})).response.statusCode).toBe(422);});
 it('revoke only removes target, idempotency returns original response without duplicate events',async()=>{const {response,payload}=await command({kind:'revoke',nodeId:id(10)});expect(response.statusCode).toBe(200);const a=accounts[0];const retry=await app.inject({method:'POST',url:'/api/v1/me/progress/commands',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload});expect(retry.json()).toEqual(response.json());const p=await progress();expect(p.unlocked.map((n:any)=>n.nodeId)).toContain(id(15));expect(p.unlocked.map((n:any)=>n.nodeId)).not.toContain(id(10));const events=await db.query<{n:string}>('SELECT count(*) AS n FROM achievement_events WHERE user_id=$1 AND idempotency_key=$2',[a.id,payload.idempotencyKey]);expect(Number(events.rows[0].n)).toBe(1);});
 it('rejects stale revisions and changed payload with a used idempotency key',async()=>{expect((await command({kind:'unlock',nodeId:id(10)},accounts[0],{expectedRevision:0})).response.statusCode).toBe(409);const a=accounts[0],result=await command({kind:'unlock',nodeId:id(10)});const retry=await app.inject({method:'POST',url:'/api/v1/me/progress/commands',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload:{...result.payload,command:{kind:'revoke',nodeId:id(10)}}});expect(retry.statusCode).toBe(409);});
 it('rejects invalid batches without partial changes',async()=>{const before=await progress(accounts[1]);expect((await command({kind:'initialize',targetNodeIds:[id(6),'BAD']},accounts[1])).response.statusCode).toBe(422);expect((await progress(accounts[1])).unlocked).toEqual(before.unlocked);});
 it('serializes simultaneous commands against the same revision',async()=>{const a=accounts[1],p=await progress(a);const send=(nodeId:string)=>app.inject({method:'POST',url:'/api/v1/me/progress/commands',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload:{idempotencyKey:randomUUID(),graphReleaseId:p.graphReleaseId,expectedRevision:p.revision,command:{kind:'initialize',targetNodeIds:[nodeId]}}});const replies=await Promise.all([send(id(1)),send(id(2))]);expect(replies.map(r=>r.statusCode).sort()).toEqual([200,409]);});
 it('rolls back progress when a transaction fails',async()=>{const before=await progress();await expect(db.transaction(async tx=>{await tx.query('DELETE FROM user_unlocked_nodes WHERE user_id=$1',[accounts[0].id]);throw new Error('simulated failure');})).rejects.toThrow('simulated failure');expect((await progress()).unlocked).toEqual(before.unlocked);});
 it('enforces module/domain foreign key and immutable releases',async()=>{await expect(db.query("UPDATE knowledge_nodes SET module_id='missing-module' WHERE id=$1",[id(0)])).rejects.toThrow();await expect(db.query("UPDATE graph_releases SET content_hash=content_hash")).rejects.toThrow('immutable');});
 it('keeps user progress after app + database close/reopen',async()=>{const before=await progress();await app.close();await db.close();db=await openDatabase(process.env.DATABASE_MODE==='postgres'?{mode:'postgres'}:{mode:'pglite',directory});app=await makeApp(db,{rateLimit:false});expect((await progress()).unlocked).toEqual(before.unlocked);});
 it('keeps progress after logout/login and invalidates old session',async()=>{const a=accounts[0],before=await progress();expect((await app.inject({method:'POST',url:'/api/v1/auth/logout',headers:{cookie:a.cookie,origin,'x-csrf-token':a.csrf},payload:{}})).statusCode).toBe(200);expect((await app.inject({url:'/api/v1/me/progress',headers:{cookie:a.cookie}})).statusCode).toBe(401);const login=await app.inject({method:'POST',url:'/api/v1/auth/login',headers:{origin},payload:{username:a.username.toUpperCase(),password:a.password}});expect(login.statusCode).toBe(200);a.cookie=login.cookies[0].name+'='+login.cookies[0].value;a.csrf=login.json().csrfToken;expect((await progress()).unlocked).toEqual(before.unlocked);});
});
