import {sceneSchema,objectSchema,type SceneDefinition} from '../../packages/ponder/src/schema';
import type {z} from 'zod';
import {geometrySystem} from '../fixtures/geometry-system';
import {setsLogicSystem} from '../fixtures/sets-logic-system';
import {probabilitySystem} from '../fixtures/probability-system';
import {sequencesSystem} from '../fixtures/sequences-system';
type O=z.input<typeof objectSchema>;type S=z.input<typeof sceneSchema>['steps'][number];type V=[string,string];type Color='cyan'|'gold'|'green'|'muted';
const p=(label:string,min:number,max:number,value:number,step=.05)=>({label,min,max,default:value,step});
const point=(id:string,label:string,at:V,color:Color='gold'):O=>({id,label,at,color,kind:'point'});
const label=(id:string,text:string,at:V,color:Color='muted'):O=>({id,label:text,at,color,kind:'label'});
const seg=(id:string,from:V,to:V,color:Color='gold',dashed=false):O=>({id,label:'',from,to,color,dashed,kind:'segment'});
const poly=(id:string,vertices:V[],color:Color='cyan'):O=>({id,label:'',vertices,color,kind:'polygon',opacity:.2});
const rect=(id:string,x:string,y:string,w:string,h:string,color:Color='cyan')=>poly(id,[[x,y],[`${x}+(${w})`,y],[`${x}+(${w})`,`${y}+(${h})`],[x,`${y}+(${h})`]],color);
const trace=(id:string,x:string,y:string,domain:[number,number],color:Color='cyan',end?:string):O=>({id,label:'',x,y,domain,color,kind:'parametric',...(end?{end}:{})});
const track=(parameter:string,from:number,to:number)=>({parameter,from,to,start:1.5,duration:6,easing:'smooth' as const});
const step=(id:string,title:string,caption:string,show:string[],extra:Partial<S>={}):S=>({id,title,caption,semanticLabel:caption,duration:10,show,cues:show.map((target,i)=>({target,kind:'draw',start:(i%5)*.3,duration:1.5})),narration:{captionAt:.2,formulaAt:2},...extra});
const nodes=[...geometrySystem.concepts,...setsLogicSystem.concepts,...probabilitySystem.concepts,...sequencesSystem.concepts];
function make(id:string,nodeId:string,objects:O[],steps:S[],parameters:SceneDefinition['parameters']={},extra:Partial<z.input<typeof sceneSchema>>={}):SceneDefinition{
 const node=nodes.find(n=>n.id===nodeId);if(!node)throw Error(`Missing batch two node ${nodeId}`);
 return sceneSchema.parse({id,nodeId,title:node.canonicalName,version:1,dslVersion:1,renderer:'geometry',pedagogy:{primary:'CONSTRUCT_PATTERN',secondary:['INVARIANT_PATTERN','COMPARE_PATTERN']},duration:steps.reduce((n,s)=>n+s.duration,0),scene:{captionPlacement:'below',axes:false,xRange:[-5,5],yRange:[-4,4],camera:[5,4,6]},parameters,expressions:{},objects,readouts:[],constraints:[],steps,controls:{supportsScrub:false,allowCameraRotation:false},completion:{principleViewed:true},textbook:{sourceRef:node.sources[0].sourceRef,scope:`${node.canonicalName}：${node.summary} 演示使用明确条件下的代表性实例；动态图与有限样本不替代证明。`},...extra});
}
const ellipse=make('ellipse-definition','HS-GEO-ELLIPSE-001',[
 trace('curve','a*cos(x)','b*sin(x)',[0,2*Math.PI]),trace('trail','a*cos(x)','b*sin(x)',[0,2*Math.PI],'cyan','theta'),trace('verticalCurve','b*cos(x)','a*sin(x)',[0,2*Math.PI]),point('vf1','F₁',['0','-c']),point('vf2','F₂',['0','c']),seg('verticalMajor',['0','-a'],['0','a'],'muted'),seg('verticalMinor',['-b','0'],['b','0'],'muted'),point('f1','F₁',['-c','0']),point('f2','F₂',['c','0']),point('moving','P',['a*cos(theta)','b*sin(theta)'],'green'),seg('r1',['-c','0'],['a*cos(theta)','b*sin(theta)']),seg('r2',['c','0'],['a*cos(theta)','b*sin(theta)'],'green'),seg('major',['-a','0'],['a','0'],'muted'),seg('minor',['0','-b'],['0','b'],'muted'),label('axisLabel','长轴 2a',['0','-.4'])
],[step('foci','固定两个焦点','焦点距离 2c 小于距离和 2a；否则不能得到非退化椭圆。',['f1','f2']),step('trace','保持距离和','移动 P，两个焦点距离一增一减，和始终为 2a。',['trail','f1','f2','moving','r1','r2'],{animate:[track('theta',0,2*Math.PI)],readouts:['sum','twiceA']}),step('axes','从距离到坐标','长半轴 a、短半轴 b 与焦半距 c 满足 a²=b²+c²。',['curve','f1','f2','major','minor','axisLabel'],{formula:String.raw`\frac{x^2}{a^2}+\frac{y^2}{b^2}=1,\quad a>b>0,\quad c^2=a^2-b^2`}),step('experiment','改变形状','调节 a、b 和点的位置；焦点随之改变，但同一条椭圆上的距离和保持 2a。',['curve','f1','f2','moving','r1','r2'],{interaction:['a','b','theta'],readouts:['sum','twiceA']}),step('vertical','识别长轴方向','焦点在 y 轴时交换 x、y 的分母。a 始终表示长半轴。',['verticalCurve','verticalMajor','verticalMinor','vf1','vf2'],{formula:String.raw`\text{焦点在 }y\text{ 轴：}\quad\frac{x^2}{b^2}+\frac{y^2}{a^2}=1`})
],{a:p('长半轴 a',3,4,3.5),b:p('短半轴 b',.6,2.5,2),theta:p('动点位置 θ',0,2*Math.PI,0,.02)},{scene:{captionPlacement:'below',axes:true,xRange:[-5,5],yRange:[-5,5]},expressions:{c:'sqrt(a^2-b^2)',d1:'sqrt((a*cos(theta)+c)^2+(b*sin(theta))^2)',d2:'sqrt((a*cos(theta)-c)^2+(b*sin(theta))^2)'},readouts:[{id:'sum',label:'PF₁+PF₂',expression:'d1+d2'},{id:'twiceA',label:'2a',expression:'2*a'}]});
const hyperbola=make('hyperbola-definition','HS-GEO-HYPERBOLA-001',[
 trace('right','a*sqrt(1+x^2)','b*x',[-2,2]),trace('verticalRight','b*x','a*sqrt(1+x^2)',[-2,2]),trace('verticalLeft','b*x','-a*sqrt(1+x^2)',[-2,2],'green'),point('vf1','F₁',['0','-c']),point('vf2','F₂',['0','c']),trace('left','-a*sqrt(1+x^2)','b*x',[-2,2],'green'),point('f1','F₁',['-c','0']),point('f2','F₂',['c','0']),point('moving','P',['side*a*sqrt(1+t^2)','b*t'],'green'),seg('r1',['-c','0'],['side*a*sqrt(1+t^2)','b*t']),seg('r2',['c','0'],['side*a*sqrt(1+t^2)','b*t'],'green'),seg('asym1',['-5','-5*b/a'],['5','5*b/a'],'muted',true),seg('asym2',['-5','5*b/a'],['5','-5*b/a'],'muted',true)
],[step('foci','确定焦点与距离差','要求 0<2a<2c。点到两焦点距离差的绝对值固定为 2a。',['f1','f2']),step('trace','沿一支移动','P 沿右支移动；两条焦点连线长度都变化，距离差的绝对值不变。',['right','f1','f2','moving','r1','r2'],{animate:[track('t',-2,2)],readouts:['difference','twiceA']}),step('branches','两支与标准方程','左右两支共同构成双曲线，不能用一支代替整个点集。',['right','left','f1','f2','asym1','asym2'],{formula:String.raw`\frac{x^2}{a^2}-\frac{y^2}{b^2}=1,\quad a,b>0,\quad c^2=a^2+b^2`}),step('experiment','检验不变量','调节参数和动点；“分支：−1 左，1 右”用于切换两支。距离差取绝对值。',['right','left','f1','f2','moving','r1','r2'],{interaction:['a','b','t','branch'],readouts:['difference','twiceA']}),step('vertical','正项决定实轴','焦点在 y 轴时，y² 项为正。虚半轴 b 无需小于 a。',['verticalRight','verticalLeft','vf1','vf2'],{formula:String.raw`\text{焦点在 }y\text{ 轴：}\quad\frac{y^2}{a^2}-\frac{x^2}{b^2}=1`})
],{a:p('实半轴 a',1,2,1.5),b:p('虚半轴 b',.6,1.4,1),t:p('动点纵向参数 t',-2,2,0),branch:p('分支：−1 左，1 右',-1,1,1,2)},{scene:{captionPlacement:'below',axes:true,xRange:[-5.5,5.5],yRange:[-5,5]},expressions:{side:'2*floor((branch+1)/2)-1',c:'sqrt(a^2+b^2)',d1:'sqrt((side*a*sqrt(1+t^2)+c)^2+(b*t)^2)',d2:'sqrt((side*a*sqrt(1+t^2)-c)^2+(b*t)^2)'},readouts:[{id:'difference',label:'|PF₁−PF₂|',expression:'abs(d1-d2)'},{id:'twiceA',label:'2a',expression:'2*a'}]});
const parabola=make('parabola-definition','HS-GEO-PARABOLA-001',[
 trace('curve','x^2/(2*p)','x',[-3,3]),point('focus','F',['p/2','0']),{kind:'line',id:'directrix',label:'',color:'gold',through:['-p/2','0'],direction:['0','1']},label('directrixLabel','准线 x=−p/2',['-p/2','3.3'],'gold'),point('moving','P',['t^2/(2*p)','t'],'green'),point('foot','H',['-p/2','t'],'muted'),seg('radius',['p/2','0'],['t^2/(2*p)','t']),seg('distance',['-p/2','t'],['t^2/(2*p)','t'],'green'),{kind:'angleMarker',id:'right',label:'',color:'muted',origin:['-p/2','t'],first:['1','0'],second:['0','1']}
],[step('focus','焦点与准线','p>0 是焦点到准线的距离；焦点为 (p/2,0)，准线为 x=−p/2。',['focus','directrix','directrixLabel']),step('equal','保持两种距离相等','PH 必须垂直于准线。P 沿曲线移动，PF 与 PH 始终相等。',['curve','focus','directrix','moving','foot','radius','distance','right'],{animate:[track('t',-3,3)],readouts:['pf','ph']}),step('equation','建立坐标方程','将点到焦点的距离与点到准线的距离相等，整理得到 y²=2px。',['curve','focus','directrix','moving','radius','distance'],{formula:String.raw`PF=PH\ \Longleftrightarrow\ y^2=2px,\quad p>0`}),step('experiment','改变开口宽度','改变 p 与 P 的位置；p 增大时，固定 y 对应的 x 减小。',['curve','focus','directrix','moving','foot','radius','distance','right'],{interaction:['p','t'],readouts:['pf','ph']}),step('directions','四种标准形式','图中向右开口；负号改变开口方向，交换 x、y 改为上下开口。',['curve','focus','directrix'],{formula:String.raw`y^2=\pm2px\quad\text{或}\quad x^2=\pm2py,\quad p>0`})
],{p:p('焦点到准线距离 p',1.2,2.5,2),t:p('动点纵坐标 y',-3,3,1)},{scene:{captionPlacement:'below',axes:true,xRange:[-2,5],yRange:[-4,4]},readouts:[{id:'pf',label:'PF',expression:'sqrt((t^2/(2*p)-p/2)^2+t^2)'},{id:'ph',label:'PH',expression:'t^2/(2*p)+p/2'}]});
const viewObjects:O[]=[rect('front','-4','-.8','w','h'),rect('side','1','-.8','d','h','green'),rect('top','1','1.9','w','d','gold'),label('frontLabel','正视图：宽 × 高',['-2.8','-1.2']),label('sideLabel','侧视图：深 × 高',['2','-1.2']),label('topLabel','俯视图：宽 × 深',['2.2','1.55']),poly('solidFront',[['-4','1.7'],['-4+w','1.7'],['-4+w','1.7+h'],['-4','1.7+h']]),poly('solidSide',[['-4+w','1.7'],['-4+w+.45*d','1.7+.25*d'],['-4+w+.45*d','1.7+h+.25*d'],['-4+w','1.7+h']],'green'),poly('solidTop',[['-4','1.7+h'],['-4+w','1.7+h'],['-4+w+.45*d','1.7+h+.25*d'],['-4+.45*d','1.7+h+.25*d']],'gold'),label('solidLabel','同一个长方体',['-2.8','1.3']),seg('widthGuide',['-4+w','1.7'],['-4+w','-.8'],'muted',true)];
const views=make('orthographic-views','HS-GEO-ORTHOGRAPHIC-VIEW-001',viewObjects,[step('solid','确定三个尺寸','以长方体为例，区分宽 w、深 d、高 h。斜画的立体图只用于辨认物体。',['solidFront','solidSide','solidTop','solidLabel']),step('front','从前面正投影','视线沿深度方向，深度被压缩；正视图保留宽和高。',['solidFront','solidSide','solidTop','front','frontLabel','widthGuide'],{animate:[track('w',1.2,2.4)]}),step('side','从侧面正投影','从右侧观察，宽度被压缩；侧视图保留深和高。',['solidFront','solidSide','solidTop','front','side','frontLabel','sideLabel'],{animate:[track('h',.8,1.5)]}),step('top','从上面正投影','高度被压缩；俯视图保留宽和深。正、俯宽相同，正、侧高相同，俯、侧深相同。',viewObjects.map(o=>o.id),{animate:[track('d',.8,1.5)]}),step('experiment','同步改变三个尺寸','分别调节宽、深、高，观察受影响的视图。此处四幅图是分区示意，不是工程三视图的展开排布。',viewObjects.map(o=>o.id),{interaction:['w','d','h'],formula:String.raw`\text{正：}(w,h)\quad\text{侧：}(d,h)\quad\text{俯：}(w,d)`})],{w:p('宽 w',1.2,2.4,1.8),d:p('深 d',.8,1.5,1.1),h:p('高 h',.8,1.5,1.2)},{scene:{captionPlacement:'below',axes:false,xRange:[-5,5],yRange:[-3,4.7]}});
function setScene(operation:'union'|'intersection'|'complement',nodeId:string){
 const symbol=operation==='union'?'A∪B':operation==='intersection'?'A∩B':'∁ᵤA',condition=operation==='union'?'属于 A 或属于 B（包含同时属于）':operation==='intersection'?'同时属于 A 和 B':'属于全集 U，但不属于 A';
 const objects:O[]=[rect('universe','-4','-1.8','8','4.4','muted'),{kind:'circle',id:'A',label:'A',color:'cyan',center:['-gap/2','.5'],radius:'1.5'},{kind:'circle',id:'B',label:'B',color:'gold',center:['gap/2','.5'],radius:'1.5'},label('labelA','A',['-gap/2','2.3'],'cyan'),label('labelB','B',['gap/2','2.3'],'gold'),label('labelU','全集 U',['-3.4','2.2']),{kind:'region',id:'result',label:symbol,color:'green',operation,first:'A',second:'B',bounds:[['-4','-1.8'],['4','2.6']]},label('resultLabel',symbol,['0','-2.2'],'green')];
 const base=objects.filter(o=>o.id!=='result'&&o.id!=='resultLabel').map(o=>o.id),all=objects.map(o=>o.id);
 return make(`set-${operation}`,nodeId,objects,[step('sets','先识别集合','矩形表示全集 U，两个圆分别表示 A、B；圆的面积不代表元素个数。',base),step('select','筛选符合条件的元素',`绿色区域表示${condition}的全部元素。`,all,{formula:operation==='union'?String.raw`A\cup B=\{x\mid x\in A\ \text{或}\ x\in B\}`:operation==='intersection'?String.raw`A\cap B=\{x\mid x\in A\ \text{且}\ x\in B\}`:String.raw`\complement_U A=\{x\in U\mid x\notin A\}`}),step('change','改变重叠范围','移动圆的位置，操作规则保持不变；重叠元素在并集中只保留一次。',all,{animate:[track('gap',.8,3.4)]}),step('experiment','尝试相交与不相交','调节圆心间距。当间距大于 3 时，两圆不相交，交集为空。补集始终相对于 U。',all,{interaction:['gap']}),step('meaning','回到元素条件',`${symbol}：${condition}。边界属于其对应集合；填色只表示集合区域。`,all)],{gap:p('两圆圆心间距',.8,3.4,1.5)},{scene:{captionPlacement:'below',axes:false,xRange:[-5,5],yRange:[-3.5,3.5]}});
}
function conditionScene(necessary:boolean){
 const objects:O[]=[{kind:'circle',id:'Q',label:'q',color:'gold',center:['0','1'],radius:'2'},{kind:'circle',id:'P',label:'p',color:'cyan',center:['0','1'],radius:'1'},label('pLabel','p：x²≤1',['0','1.5'],'cyan'),label('qLabel','q：x²≤4',['0','2.65'],'gold'),point('counter','x=1.5：q 真、p 假',['1.5','1'],'green'),point('input','当前 x',['x0','1'],'green')];
 const all=objects.map(o=>o.id);
 return make(necessary?'necessary-condition':'sufficient-condition',necessary?'HS-LOGIC-NECESSARY-001':'HS-LOGIC-SUFFICIENT-001',objects,[step('sets','把条件看成解集','内圆代表满足 p 的输入集合，外圆代表满足 q 的输入集合。输入沿横向刻度示意位置。',['Q','P','pLabel','qLabel']),step('implies','检查推出方向','满足 x²≤1 的输入一定满足 x²≤4，所以 p⇒q。',['Q','P','pLabel','qLabel','input'],{animate:[track('x0',-1,1)],readouts:['pTruth','qTruth']}),step('name',necessary?'必要条件的方向':'充分条件的方向',necessary?'q 是 p 的必要条件：p 成立必须有 q 成立。q 不成立则 p 不成立。':'p 是 q 的充分条件：p 成立足以保证 q 成立。不能据此说 q 足以推出 p。',['Q','P','pLabel','qLabel'],{formula:String.raw`p\Rightarrow q\quad\Longleftrightarrow\quad P\subseteq Q`}),step('converse','反例检验逆向','x=1.5 满足 q，却不满足 p。因此 q⇒p 不成立；充分与必要不能随意交换。',all.filter(id=>id!=='input'),{animate:[track('x0',1.5,1.5)],readouts:['pTruth','qTruth']}),step('experiment','改变输入检查真假','调节 x。读数 1 表示成立，0 表示不成立；永远不会出现 p 真而 q 假。',all.filter(id=>id!=='counter'),{interaction:['x0'],readouts:['pTruth','qTruth']})],{x0:p('输入 x',-2.5,2.5,1.5)},{readouts:[{id:'pTruth',label:'p 成立（1/0）',expression:'max(0,min(1,floor(2-abs(x0))))'},{id:'qTruth',label:'q 成立（1/0）',expression:'max(0,min(1,floor(3-abs(x0))))'}],scene:{captionPlacement:'below',axes:false,xRange:[-4,5],yRange:[-3,4]}});
}
const frequency=make('frequency-stability','HS-STAT-CLT-001',[
 {kind:'plot',id:'first',label:'试验 1',color:'cyan',expression:'5*frequency(100*x,.5,seed)',domain:[.01,10],end:'n/100'}, {kind:'plot',id:'second',label:'试验 2',color:'gold',expression:'5*frequency(100*x,.5,6)',domain:[.01,10],end:'n/100'}, {kind:'plot',id:'third',label:'试验 3',color:'green',expression:'5*frequency(100*x,.5,8)',domain:[.01,10],end:'n/100'},seg('probability',['0','2.5'],['10','2.5'],'muted',true),seg('xAxis',['0','0'],['10','0'],'muted'),seg('yAxis',['0','0'],['0','5'],'muted'),label('axisN','试验次数：0 → 1000',['5','-.45']),label('axisF','频率 1',['.7','5.4']),label('half','理论概率 0.5',['5','4.3']),point('current','当前频率',['n/100','5*frequency(n,.5,seed)'],'cyan')
],[step('experiment','明确试验条件','每条轨迹是成功概率 0.5 的独立重复伯努利试验。固定种子用于重放模拟。',['first','probability','xAxis','yAxis','axisN','axisF','half','current'],{animate:[track('n',1,30)],readouts:['count','freq']}),step('grow','增加试验次数','观察频率上下波动；次数增加时通常更稳定，不保证每次都更接近 0.5。',['first','probability','xAxis','yAxis','axisN','half','current'],{animate:[track('n',30,1000)],readouts:['count','freq']}),step('compare','比较多次独立模拟','三条轨迹不同，仍可在较大样本量下观察到较小波动；个别轨迹不能构成定理证明。',['first','second','third','probability','xAxis','yAxis','axisN','half'],{formula:String.raw`f_n=\frac{N_n}{n},\quad\operatorname{Var}(f_n)=\frac{p(1-p)}{n}\quad(\text{独立同分布})`}),step('try','回看短样本与长样本','调节次数与第一条轨迹种子。数据由相同独立试验模型生成；换种子不会挑选趋近更好的结果。',['first','second','third','probability','xAxis','yAxis','axisN','half','current'],{interaction:['n','seed'],readouts:['count','freq','error']}),step('boundary','理解稳定性的边界','稳定性以独立、相同成功概率为条件；有限频率不必等于概率，不能解释为绝对误差单调减小。',['first','second','third','probability','xAxis','yAxis','axisN','half'],{readouts:['count','freq','error']})
],{n:p('试验次数 n',1,1000,1,1),seed:p('第一条轨迹种子',1,5,1,1)},{scene:{captionPlacement:'below',axes:false,xRange:[-1,11],yRange:[-2,6]},readouts:[{id:'count',label:'次数 n',expression:'floor(n)'},{id:'freq',label:'第一条频率',expression:'frequency(n,.5,seed)'},{id:'error',label:'绝对误差',expression:'abs(frequency(n,.5,seed)-.5)'}]});
const dice:O[]=Array.from({length:6},(_,i)=>({kind:'circle',id:`die${i}`,label:String(i+1),color:'muted',center:[String(i-2.5),'1'],radius:'.36'}));
const classical=make('classical-probability','HS-PROB-CLASSICAL-001',[
 ...dice,...Array.from({length:6},(_,i)=>label(`number${i}`,String(i+1),[String(i-2.5),'.9'],'gold')),rect('favorable','-3','.5','floor(k)','1','green'),label('space','公平骰子：六个等可能基本结果',['0','2.5']),label('event','事件 A：点数 ≤ k',['0','-.2'],'green')
],[step('space','先确定有限样本空间','公平骰子六个基本结果等可能，样本空间 Ω={1,2,3,4,5,6}。',[...dice.map(o=>o.id),'space',...Array.from({length:6},(_,i)=>`number${i}`)]),step('event','选择有利结果','事件 A 是“点数不超过 k”；绿色区域覆盖有利基本结果。', [...dice.map(o=>o.id),'space','favorable','event',...Array.from({length:6},(_,i)=>`number${i}`)],{animate:[track('k',1,4)],readouts:['favorableCount','prob']}),step('ratio','计数得到概率','共有 k 个有利结果、6 个等可能结果，因此概率为 k/6。', ['favorable','event','space',...dice.map(o=>o.id),...Array.from({length:6},(_,i)=>`number${i}`)],{formula:String.raw`P(A)=\frac{|A|}{|\Omega|}=\frac{k}{6}`,readouts:['favorableCount','prob']}),step('try','改变事件','调节 k，观察事件包含的基本结果与概率同步变化。非整数 k 按向下取整计数。',['favorable','event','space',...dice.map(o=>o.id),...Array.from({length:6},(_,i)=>`number${i}`)],{interaction:['k'],readouts:['favorableCount','prob']}),step('boundary','等可能条件不可省略','如果骰子各面概率不同，不能继续用个数比；需要将有利结果的各自概率相加。',['space',...dice.map(o=>o.id),...Array.from({length:6},(_,i)=>`number${i}`)])
],{k:p('事件上界 k',1,6,3,1)},{readouts:[{id:'favorableCount',label:'有利结果个数',expression:'floor(k)'},{id:'prob',label:'P(A)',expression:'floor(k)/6'}]});
let state=29;const random=()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/4294967296;};
const randomPoints:V[]=Array.from({length:160},()=>[(6*random()-3).toFixed(5),(3*random()).toFixed(5)]);
const geometric=make('geometric-probability','HS-PROB-GEOMETRIC-001',[
 rect('space','-3','0','6','3','muted'),rect('event','-3','0','w','3','green'),label('spaceLabel','均匀落点区域 Ω：6 × 3',['0','3.4']),label('eventLabel','事件 A：左侧宽度 w 的区域',['0','-.4'],'green'),{kind:'samples',id:'drops',label:'均匀落点',color:'gold',points:randomPoints,count:'count'}
],[step('uniform','明确均匀分布','在矩形 Ω 中按面积均匀选点，等面积区域才具有相同概率。',['space','spaceLabel']),step('area','确定有利区域','绿色区域 A 的面积为 3w，Ω 的面积为 18。',['space','event','spaceLabel','eventLabel'],{animate:[track('w',1,4)],readouts:['area','prob']}),step('sample','观察随机落点','逐个显示均匀模拟点。有限落点比例会波动，理论概率仍由面积比给出。',['space','event','spaceLabel','eventLabel','drops'],{animate:[track('count',1,160)],readouts:['prob']}),step('try','改变有利区域','调节 w，面积比随之改变。点落在边界的概率为零，不影响此连续模型的概率。',['space','event','spaceLabel','eventLabel','drops'],{interaction:['w'],formula:String.raw`P(A)=\frac{\text{面积}(A)}{\text{面积}(\Omega)}=\frac{3w}{18}=\frac{w}{6}`,readouts:['area','prob']}),step('boundary','区分长度、面积和体积','本例使用面积比。线段上均匀选点用长度比，空间均匀选点用体积比；非均匀分布不能直接套测度比。',['space','event','spaceLabel','eventLabel'],{readouts:['prob']})
],{w:p('有利区域宽 w',.5,5.5,2),count:p('显示落点个数',1,160,1,1)},{scene:{captionPlacement:'below',axes:false,xRange:[-4.5,4.5],yRange:[-3,4]},readouts:[{id:'area',label:'有利面积',expression:'3*w'},{id:'prob',label:'P(A)',expression:'w/6'}]});
function sequenceScene(geometric:boolean){
 const f=geometric?'a1*q^(x-1)':'a1+(x-1)*d';
 const objects:O[]=[{kind:'plot',id:'continuous',label:geometric?'连续指数延拓':'连续一次延拓',color:'muted',expression:f,domain:[1,6]},{kind:'samples',id:'terms',label:'数列项',color:'cyan',points:Array.from({length:6},(_,i)=>[String(i+1),geometric?`a1*q^${i}`:`a1+${i}*d`] as V),count:'count'},label('domainLabel','数列只取正整数序号；灰色曲线是连续延拓',['3.5',geometric?'10.5':'3.8'])];
 return make(geometric?'geometric-exponential':'arithmetic-linear',geometric?'HS-GP-EXPONENTIAL-001':'HS-AP-LINEAR-001',objects,[step('terms','从离散项开始',geometric?'相邻两项比值恒为 q，蓝点代表正整数序号对应的数列项。':'相邻两项差值恒为 d，蓝点代表正整数序号对应的数列项。',['terms'],{animate:[track('count',1,6)]}),step('extend','补出连续函数',geometric?'用 F(x)=a₁q^(x−1) 延拓。正整数处的函数值恰好是数列各项。':'用 F(x)=a₁+(x−1)d 延拓。正整数处的函数值恰好是数列各项。',['continuous','terms','domainLabel'],{formula:geometric?String.raw`a_n=a_1q^{n-1}=\frac{a_1}{q}\,q^n,\quad n\in\mathbb N^*`:String.raw`a_n=a_1+(n-1)d=dn+(a_1-d),\quad n\in\mathbb N^*`}),step('change','改变共同参数',geometric?'改变正公比 q。0<q<1 时递减，q>1 时递增；q=1 时成为常数列。':'改变 d；它是延拓直线的斜率。d>0 递增，d<0 递减，d=0 为常数列。',['continuous','terms','domainLabel'],{animate:[track(geometric?'q':'d',geometric?.65:-.6,geometric?1.45:.6)]}),step('try','同时检查点与曲线','调节首项与共同参数；蓝点始终落在对应的连续曲线上。',['continuous','terms','domainLabel'],{interaction:geometric?['a1','q']:['a1','d']}),step('boundary','区分定义域与退化情形',geometric?'这里只演示 a₁>0、q>0。q=1 时延拓是常函数；a₁/q 是比例系数，一般并非直接等于 qˣ。负公比不适用实指数延拓。':'数列定义域是正整数，直线延拓定义域为实数；d=0 时延拓为常函数，不能称为一次函数。',['continuous','terms','domainLabel'])],geometric?{a1:p('首项 a₁',.5,1.5,1),q:p('正公比 q',.6,1.5,1.3),count:p('显示项数',1,6,1,1)}:{a1:p('首项 a₁',-1,1,0),d:p('公差 d',-.6,.6,.5),count:p('显示项数',1,6,1,1)},{renderer:'coordinate',scene:{captionPlacement:'below',axes:true,xRange:[-.5,7],yRange:geometric?[-3,12]:[-5,5]},expressions:{f}});
}
export const batchTwoScenes=[ellipse,parabola,hyperbola,views,setScene('union','HS-SET-UNION-001'),setScene('intersection','HS-SET-INTERSECTION-001'),setScene('complement','HS-SET-COMPLEMENT-001'),conditionScene(false),conditionScene(true),frequency,classical,geometric,sequenceScene(false),sequenceScene(true)];
