import {sceneSchema,type SceneDefinition,type SceneObject} from '../../packages/ponder/src/schema';
import {geometrySystem} from '../fixtures/geometry-system';

type V2=[string,string];type V3=[string,string,string];type O=SceneObject;
type Input={index:number;id:string;renderer:'geometry'|'coordinate'|'solid';objects:O[];parameters:SceneDefinition['parameters'];readouts:SceneDefinition['readouts'];captions:[string,string,string,string,string];formula:string;intro:string[];focus:string[];animate:[string,number,number];xRange?:[number,number];yRange?:[number,number];expressions?:Record<string,string>;camera?:V3};
const p=(label:string,min:number,max:number,value:number,step=.05)=>({label,min,max,default:value,step});
const pt=(id:string,label:string,at:V2,color:O['color']='gold'):O=>({kind:'point',id,label,at,color});
const s=(id:string,from:V2,to:V2,color:O['color']='cyan',dashed=false):O=>({kind:'segment',id,label:'',from,to,color,dashed,arrow:false});
const poly=(id:string,vertices:V2[],color:O['color']='cyan'):O=>({kind:'polygon',id,label:'',vertices,color,opacity:.22});
const rect=(id:string,x:string,y:string,w:string,h:string,color:O['color']='cyan'):O=>poly(id,[[x,y],[`(${x})+(${w})`,y],[`(${x})+(${w})`,`(${y})+(${h})`],[x,`(${y})+(${h})`]],color);
const circle=(id:string,center:V2,radius:string,color:O['color']='cyan'):O=>({kind:'circle',id,label:'',center,radius,color});
const line=(id:string,through:V2,direction:V2,color:O['color']='cyan'):O=>({kind:'line',id,label:'',through,direction,color});
const curve=(id:string,x:string,y:string,domain:[number,number],color:O['color']='cyan'):O=>({kind:'parametric',id,label:'',x,y,domain,color});
const P=(id:string,label:string,origin:V3=['0','0','0'],u:V3=['1','0','0'],v:V3=['0','0','1'],color:O['color']='muted'):O=>({kind:'plane',id,label,origin,u,v,size:2,color});
const L=(id:string,label:string,origin:V3,direction:V3,color:O['color']='cyan'):O=>({kind:'line3',id,label,origin,direction,length:4,color,auxiliary:false});
const S=(id:string,from:V3,to:V3,color:O['color']='gold'):O=>({kind:'segment3',id,label:'',from,to,color,auxiliary:false});
const Q=(id:string,label:string,at:V3,color:O['color']='gold'):O=>({kind:'point3',id,label,at,color});
const ro=(id:string,label:string,expression:string):SceneDefinition['readouts'][number]=>({id,label,expression});
const common=geometrySystem.concepts;
function make(c:Input):SceneDefinition{
 const node=common[c.index-1];if(!node)throw Error(`Unknown geometry node ${c.index}`);
 const all=c.objects.map(o=>o.id),step=(id:string,title:string,caption:string,show:string[],extra:Record<string,unknown>={})=>({id,title,caption,semanticLabel:caption,duration:10,show,readouts:c.readouts.map(r=>r.id),highlight:[],interaction:[],cues:show.map((target,i)=>({target,kind:'draw',start:(i%5)*.25,duration:1.3})),narration:{captionAt:.2,formulaAt:2},animate:[],...extra});
 const [key,from,to]=c.animate;
 return sceneSchema.parse({id:c.id,nodeId:node.id,title:node.canonicalName,version:1,dslVersion:1,renderer:c.renderer,pedagogy:{primary:c.renderer==='solid'?'SPATIAL_REASONING':'PARAMETER_PATTERN',secondary:['CONSTRUCT_PATTERN','COMPARE_PATTERN']},duration:50,scene:{captionPlacement:'below',axes:c.renderer==='coordinate',xRange:c.xRange??[-5,5],yRange:c.yRange??[-4,4],camera:c.camera??[6,5,7]},parameters:c.parameters,expressions:c.expressions??{},objects:c.objects,readouts:c.readouts,constraints:[],steps:[step('objects','先辨认对象',c.captions[0],c.intro),step('construct','构造关系',c.captions[1],c.focus),step('change','观察变化',c.captions[2],all,{animate:[{parameter:key,from,to,start:1,duration:8,easing:'smooth'}]}),step('explore','自己检验',c.captions[3],all,{interaction:Object.keys(c.parameters)}),step('conclude','条件与结论',c.captions[4],all,{formula:c.formula})],controls:{supportsScrub:false,allowCameraRotation:c.renderer==='solid'},completion:{principleViewed:true},textbook:{sourceRef:node.sources[0].sourceRef,scope:`${node.canonicalName}。${node.summary} 图形仅展示明确参数条件下的模型；有限观察不代替一般证明。`}});
}
const scenes:Input[]=[];
const add=(c:Input)=>scenes.push(c);

// 1–12: geometric objects and projection. Each specimen has its own construction.
add({index:1,id:'geometry-basic-objects',renderer:'solid',parameters:{height:p('点的离面高度',0,2,1)},objects:[P('plane','平面 α'),L('line','直线 l',['0','0','0'],['1','0','0']),Q('on','面内点 A',['.7','0','.5']),Q('off','面外点 P',['.7','height','.5']),S('drop',['.7','0','.5'],['.7','height','.5'])],readouts:[ro('h','P 到平面的垂直距离','height')],captions:['平面、直线、点是基本对象；图中平面片只代表无限平面。','A 在平面内，l 也在平面内；P 的高度决定它是否在平面上。','让 P 接近平面，观察点与平面的隶属关系变化。','把高度调到 0，P 落在平面上；非零时不在。','点是否在直线上、直线是否在平面内须分别判断。'],formula:String.raw`A\in\alpha,\quad l\subset\alpha,\quad P\in\alpha\iff h=0`,intro:['plane','line','on'],focus:['plane','line','on','off','drop'],animate:['height',1,0]});
add({index:2,id:'geometry-space-axioms',renderer:'solid',parameters:{height:p('第四点的高度',0,2,1)},objects:[P('alpha','平面 α'),Q('A','A',['-1','0','-1']),Q('B','B',['1','0','-1']),Q('C','C',['0','0','1']),Q('D','D',['0','height','.2']),L('AB','直线 AB',['0','0','-1'],['1','0','0']),S('alt',['0','0','.2'],['0','height','.2'],'green')],readouts:[ro('h','D 到平面的距离','height')],captions:['先给出不共线的 A、B、C。','这三个点确定唯一平面；A、B 同时确定直线 AB。','移动 D 检查它是否也属于该平面。','高度为 0 时 D 在平面内；这不会改变前三点确定的平面。','基本事实给出点、线、面的隶属与唯一性，画出的有限片不是证明。'],formula:String.raw`A,B,C\text{ 不共线}\Rightarrow\exists!\,\alpha\text{ 经过三点}`,intro:['A','B','C'],focus:['alpha','A','B','C','AB','D'],animate:['height',1,0]});
add({index:3,id:'geometry-plane-determination',renderer:'solid',parameters:{offset:p('第三点到直线的偏移',0,2,1)},objects:[L('base','AB',['0','0','0'],['1','0','0']),Q('A','A',['-1','0','0']),Q('B','B',['1','0','0']),Q('C','C',['0','0','offset']),P('alpha','候选平面 α')],readouts:[ro('distance','C 到 AB 的偏移','offset')],captions:['先用两个不同点画出 AB。','第三点 C 不在 AB 上时，可唯一确定平面。','让 C 向 AB 靠近，观察不共线条件退化。','偏移为零时三点共线，存在无数个过 AB 的平面。','判定条件是三个不共线点，不能省略“不共线”。'],formula:String.raw`C\notin AB\Rightarrow\exists!\,\alpha:\ A,B,C\in\alpha`,intro:['A','B','base'],focus:['A','B','base','C','alpha'],animate:['offset',1,0]});
add({index:4,id:'geometry-intersections',renderer:'solid',parameters:{height:p('直线高度',-1,1,1)},objects:[P('alpha','平面 α'),L('a','直线 a',['0','height','0'],['1','-.5','0']),Q('hit','交点',['2*height','0','0'],'green'),P('beta','平面 β',['0','0','0'],['0','1','0'],['0','0','1'],'green'),L('seam','交线',['0','0','0'],['0','0','1'],'gold')],readouts:[ro('intersectionX','a 与 α 交点横坐标','2*height')],captions:['两个平面有公共部分时，公共部分形成交线。','斜线 a 与 α 相交，交点坐标由两者方程共同满足。','改变 a 的高度，交点沿 α 移动。','移动高度并旋转视角；屏幕上的交叉未必是空间相交。','本图 α:y=0、β:x=0，交线是 y=x=0；a 的交点满足 y=0。'],formula:String.raw`\alpha\cap\beta=l,\qquad a\cap\alpha=\{P\}`,intro:['alpha','beta','seam'],focus:['alpha','a','hit'],animate:['height',1,-1]});
add({index:5,id:'geometry-prism',renderer:'solid',parameters:{height:p('棱柱高 h',.7,2.5,1.5)},objects:[S('base1',['-1','0','-1'],['1','0','-1']),S('base2',['1','0','-1'],['0','0','1']),S('base3',['0','0','1'],['-1','0','-1']),S('top1',['-1','height','-1'],['1','height','-1'],'green'),S('top2',['1','height','-1'],['0','height','1'],'green'),S('top3',['0','height','1'],['-1','height','-1'],'green'),S('edge1',['-1','0','-1'],['-1','height','-1']),S('edge2',['1','0','-1'],['1','height','-1']),S('edge3',['0','0','1'],['0','height','1'])],readouts:[ro('h','底面间的垂直距离','height')],captions:['底面是两个全等三角形。','对应顶点连成互相平行的侧棱；上下底面平行。','改变高度，底面形状与侧棱平行关系保持。','对照上下三角形与三条侧棱，辨认棱柱结构。','这里只画三棱柱；一般棱柱的侧面是平行四边形。'],formula:String.raw`\text{上、下底面全等且平行}`,intro:['base1','base2','base3'],focus:['base1','base2','base3','top1','top2','top3','edge1','edge2','edge3'],animate:['height',1.5,2.4]});
add({index:6,id:'geometry-pyramid',renderer:'solid',parameters:{height:p('锥顶高度 h',.5,2.5,1.6)},objects:[S('base1',['-1','0','-1'],['1','0','-1']),S('base2',['1','0','-1'],['0','0','1']),S('base3',['0','0','1'],['-1','0','-1']),Q('apex','顶点 V',['0','height','0']),S('edge1',['-1','0','-1'],['0','height','0'],'gold'),S('edge2',['1','0','-1'],['0','height','0'],'gold'),S('edge3',['0','0','1'],['0','height','0'],'gold')],readouts:[ro('h','底面到顶点高度','height')],captions:['三角形作为底面。','各侧面共享同一个锥顶 V；侧棱在 V 汇合。','提高锥顶，底面不变而各侧面的形状改变。','对照棱柱：棱锥只有一个底面，侧面是三角形。','这里只画三棱锥；底面可为任意多边形。'],formula:String.raw`\text{每个侧面都是以 }V\text{ 为公共顶点的三角形}`,intro:['base1','base2','base3'],focus:['base1','base2','base3','apex','edge1','edge2','edge3'],animate:['height',1.6,2.4]});
add({index:7,id:'geometry-solids-of-revolution',renderer:'geometry',parameters:{radius:p('截面半径 r',.5,1.2,.8),height:p('轴向高度 h',1,3,2)},objects:[s('axisCylinder',['-3','-2'],['-3','2'],'muted',true),s('axisCone',['0','-2'],['0','2'],'muted',true),s('axisSphere',['3','-2'],['3','2'],'muted',true),rect('cylinder','-3-radius','-height/2','2*radius','height'),poly('cone',[['-radius','-height/2'],['radius','-height/2'],['0','height/2']],'gold'),circle('sphere',['3','0'],'radius','green'),s('r',['3','0'],['3+radius','0'],'gold')],readouts:[ro('diameter','底面直径','2*radius'),ro('h','轴向高度','height')],captions:['三个轴截面依次代表圆柱、圆锥和球。','矩形、直角三角形、半圆分别绕轴旋转生成对应旋转体。','改变半径，三个轴截面的横向尺寸同步变化。','分别辨认平面母形与空间旋转体；画面仅是轴截面示意。','球由半圆绕直径旋转形成；圆锥由直角三角形绕直角边形成。'],formula:String.raw`\text{旋转体由平面图形绕固定轴旋转生成}`,intro:['axisCylinder','cylinder'],focus:['axisCylinder','axisCone','axisSphere','cylinder','cone','sphere','r'],animate:['radius',.7,1.1]});
add({index:8,id:'geometry-polyhedron-or-revolution',renderer:'geometry',parameters:{radius:p('旋转截面半径 r',.6,1.6,1.3)},objects:[poly('polygon',[['-3','-1'],['-2','-1.5'],['-1','-1'],['-1','1'],['-2','1.5'],['-3','1']]),circle('round',['2','0'],'radius','green'),s('axis',['2','-1.8'],['2','1.8'],'gold',true),pt('facet','平面面',['-2','1.5']),pt('curveSurface','曲面',['2+radius','0'],'green')],readouts:[ro('r','旋转截面半径','radius')],captions:['左侧物体用平面多边形面围成，右侧示意旋转曲面。','逐一辨认“面是否为多边形”与“是否绕轴旋转生成”。','改变旋转体截面半径，左侧多边形仍按平面面分类。','这张图是两类表面截面示意，不表示每个旋转体都只有曲面。','圆柱和圆锥也有平面底面；分类看生成方式与侧面结构。'],formula:String.raw`\text{多面体：多边形面围成；旋转体：绕轴旋转生成}`,intro:['polygon','facet'],focus:['polygon','facet','round','axis','curveSurface'],animate:['radius',1.3,1.6]});
add({index:9,id:'geometry-oblique-projection',renderer:'geometry',parameters:{depth:p('真实深度 d',.5,3,2),ratio:p('斜轴比例',.3,.8,.5)},objects:[rect('face','-2','-1','2','2'),s('depth1',['0','-1'],['ratio*depth/sqrt(2)','-1+ratio*depth/sqrt(2)'],'gold'),s('depth2',['0','1'],['ratio*depth/sqrt(2)','1+ratio*depth/sqrt(2)'],'gold'),s('depth3',['-2','1'],['-2+ratio*depth/sqrt(2)','1+ratio*depth/sqrt(2)'],'gold'),s('top',['-2+ratio*depth/sqrt(2)','1+ratio*depth/sqrt(2)'],['ratio*depth/sqrt(2)','1+ratio*depth/sqrt(2)'],'green'),s('side',['ratio*depth/sqrt(2)','-1+ratio*depth/sqrt(2)'],['ratio*depth/sqrt(2)','1+ratio*depth/sqrt(2)'],'green')],readouts:[ro('projected','斜轴画出长度','ratio*depth'),ro('actual','真实深度','depth')],captions:['先画正面的矩形，宽高按原尺度保留。','深度方向沿 45° 斜轴，斜二测通常取原长度的一半。','改变真实深度，平行边的投影仍平行。','调整比例，对比画出长度和真实深度；图中比例只是约定。','斜二测不是正投影，不能从斜边画长直接读出真实深度。'],formula:String.raw`d_{\text{图}}=\frac12d_{\text{实}}\quad(\text{常用斜二测约定})`,intro:['face'],focus:['face','depth1','depth2','depth3','top','side'],animate:['depth',2,3]});
add({index:11,id:'geometry-reconstruct-from-views',renderer:'geometry',parameters:{depth:p('候选深度 d',.7,2.5,1.2)},objects:[rect('front','-4','-2','2','2'),rect('side','0','-2','depth','2','green'),rect('top','0','1','2','depth','gold'),poly('solidFront',[['-4','1'],['-2','1'],['-2','2.5'],['-4','2.5']]),poly('solidSide',[['-2','1'],['-2+depth*.5','1+depth*.35'],['-2+depth*.5','2.5+depth*.35'],['-2','2.5']],'green')],readouts:[ro('depthValue','从侧视图读出的深度','depth')],captions:['正视图给宽与高，缺少深度。','侧视图补充深度；俯视图同时校验宽与深。','改变候选深度，只有侧视、俯视对应尺寸也变时才一致。','逐个检查三个方向；只看一个视图通常无法唯一还原。','同一组三视图可能对应多个不同内部结构，需结合轮廓与附加信息。'],formula:String.raw`\text{正视：宽高；侧视：深高；俯视：宽深}`,intro:['front'],focus:['front','side','top','solidFront','solidSide'],animate:['depth',1.2,2.2]});
add({index:12,id:'geometry-composite-solids',renderer:'geometry',parameters:{topHeight:p('上部高度',.5,2,1)},objects:[rect('base','-2','-2','4','1.5'),poly('roof',[['-2','-.5'],['2','-.5'],['0','-.5+topHeight']],'gold'),s('split',['-2','-.5'],['2','-.5'],'green',true),pt('whole','组合体',['0','-1.2'])],readouts:[ro('h','上部高度','topHeight'),ro('total','总体高度','1.5+topHeight')],captions:['先辨认下部棱柱的正面截面。','上部棱锥与下部棱柱沿公共底面拼接。','改变上部高度，外轮廓与总体高度一起变。','分割线是内部公共面，不是最终外表面。','求组合体表面积时公共贴合面不能重复计入。'],formula:String.raw`S_{\text{外}}=S_1+S_2-2S_{\text{贴合}}`,intro:['base'],focus:['base','roof','split','whole'],animate:['topHeight',1,1.8]});

// 13–20: unfold, compare dimensions, and compute area or volume from one parameter source.
add({index:13,id:'geometry-surface-area',renderer:'geometry',parameters:{edge:p('正方体棱长 a',.7,1.7,1)},objects:[rect('center','-edge/2','-edge/2','edge','edge'),rect('left','-1.5*edge','-edge/2','edge','edge','gold'),rect('right','edge/2','-edge/2','edge','edge','gold'),rect('top','-edge/2','edge/2','edge','edge','green'),rect('bottom','-edge/2','-1.5*edge','edge','edge','green'),rect('flap','1.5*edge','-edge/2','edge','edge','muted')],readouts:[ro('face','单面面积','edge^2'),ro('total','六面总面积','6*edge^2')],captions:['一个面是边长 a 的正方形。','展开正方体，六个面不重叠地铺开。','改变棱长，六个面的面积同时按 a² 变化。','逐个核对六片，贴合边不产生额外面积。','该例是正方体；一般几何体应按实际外表面分别求和。'],formula:String.raw`S_{\text{正方体}}=6a^2`,intro:['center'],focus:['center','left','right','top','bottom','flap'],animate:['edge',1,1.6]});
add({index:14,id:'geometry-prism-surface-area',renderer:'geometry',parameters:{width:p('底边 a',.8,2,1.4),height:p('棱柱高 h',1,2.5,1.6)},objects:[rect('front','-width/2','-1','width','height'),rect('back','width/2','-1','width','height','green'),rect('left','-1.5*width','-1','width','height','gold'),rect('right','1.5*width','-1','width','height','gold'),rect('base','-width/2','-1-width','width','width','green'),rect('top','-width/2','-1+height','width','width','green')],readouts:[ro('lateral','四个侧面面积','4*width*height'),ro('bases','两个底面面积','2*width^2'),ro('total','总表面积','4*width*height+2*width^2')],captions:['以底面为正方形的直棱柱为例。','四个矩形侧面展开成侧面带，另有两个底面。','改变高度，侧面积变而底面积保持。','改变底边或高度，逐项对照侧面和底面读数。','一般棱柱的表面积仍是侧面积加两个底面积；不能对斜棱柱直接套直棱柱侧面积公式。'],formula:String.raw`S_{\text{直四棱柱}}=4ah+2a^2`,intro:['front','base'],focus:['front','back','left','right','base','top'],animate:['height',1.6,2.3]});
add({index:15,id:'geometry-pyramid-surface-area',renderer:'geometry',parameters:{base:p('正方形底边 a',.8,2,1.4),slant:p('侧面斜高 l',1.1,1.8,1.4)},objects:[rect('baseFace','-base/2','-base/2','base','base'),poly('north',[['-base/2','base/2'],['base/2','base/2'],['0','base/2+slant']],'gold'),poly('south',[['-base/2','-base/2'],['base/2','-base/2'],['0','-base/2-slant']],'gold'),poly('west',[['-base/2','-base/2'],['-base/2','base/2'],['-base/2-slant','0']],'green'),poly('east',[['base/2','-base/2'],['base/2','base/2'],['base/2+slant','0']],'green')],readouts:[ro('baseArea','底面积','base^2'),ro('sideArea','四侧面面积','2*base*slant'),ro('total','总表面积','base^2+2*base*slant')],captions:['以正四棱锥为例：底面正方形，四个侧面全等。','每个侧面三角形面积为 a·l/2，斜高须大于底边的一半。','改变斜高，侧面三角形改变而底面不变。','对照 4 个侧面与 1 个底面；l 是侧面斜高，不是锥体垂直高。','非正棱锥必须逐个计算侧面三角形，不能默认斜高相同。'],formula:String.raw`S_{\text{正四棱锥}}=a^2+4\cdot\frac{al}{2}`,intro:['baseFace'],focus:['baseFace','north','south','west','east'],animate:['slant',1.4,1.7]});
add({index:16,id:'geometry-cylinder-surface-area',renderer:'geometry',parameters:{radius:p('底面半径 r',.6,1.5,1),height:p('圆柱高 h',.8,2,1.4)},objects:[rect('lateral','-3','-height/2','2*pi*radius','height'),circle('base1',['-2','2'],'radius','gold'),circle('base2',['2','2'],'radius','gold'),s('circumference',['-3','-height/2'],['-3+2*pi*radius','-height/2'],'green')],readouts:[ro('around','底面周长','2*pi*radius'),ro('sideArea','侧面积','2*pi*radius*height'),ro('total','总表面积','2*pi*radius*height+2*pi*radius^2')],captions:['圆柱底面半径 r、高 h。','侧面展开为长 2πr、高 h 的矩形，加两个圆形底面。','改变半径，矩形展开长度随底面周长同步变化。','对照周长与矩形长；图中矩形可能超出视野，可缩小 r。','侧面无接缝重叠时，表面积是一个侧面加两个底面。'],formula:String.raw`S=2\pi rh+2\pi r^2`,intro:['base1','base2'],focus:['base1','base2','lateral','circumference'],animate:['radius',1,.6],xRange:[-4,7],yRange:[-4,4]});
add({index:17,id:'geometry-cone-surface-area',renderer:'geometry',parameters:{radius:p('底面半径 r',.5,1.3,.8),slant:p('母线长 l',1.5,3,2.2)},objects:[circle('bottom',['-2','0'],'radius','green'),{kind:'parametric',id:'arc',label:'扇形弧',color:'cyan',x:'2+slant*cos(x)',y:'slant*sin(x)',domain:[0,2*Math.PI],end:'2*pi*radius/slant'},s('radius1',['2','0'],['2+slant','0'],'gold'),s('radius2',['2','0'],['2+slant*cos(2*pi*radius/slant)','slant*sin(2*pi*radius/slant)'],'gold'),pt('apex','扇形圆心',['2','0'])],readouts:[ro('circumference','底面周长','2*pi*radius'),ro('angle','展开扇形圆心角（弧度）','2*pi*radius/slant'),ro('sideArea','侧面积','pi*radius*slant'),ro('total','总表面积','pi*radius*slant+pi*radius^2')],captions:['圆锥底面半径 r，母线长 l；本场景始终令 l>r。','侧面展开为半径 l 的扇形；扇形弧长须等于底面周长 2πr。','改变 r，扇形角度读数随 2πr/l 变化。','弧线与两条母线共同围成侧面展开图；扇形无重叠。','圆锥侧面积 πrl，另加一个底面积 πr²。'],formula:String.raw`l\theta=2\pi r,\qquad S=\pi rl+\pi r^2`,intro:['bottom','apex'],focus:['bottom','arc','radius1','radius2','apex'],animate:['radius',.8,1.2],xRange:[-4,6]});
add({index:18,id:'geometry-prism-volume',renderer:'geometry',parameters:{base:p('底边 a',.8,2,1.5),height:p('柱高 h',.5,2.5,1.5)},objects:[rect('front','-base/2','-1','base','height'),poly('top',[['-base/2','-1+height'],['base/2','-1+height'],['base/2+.5*base','-1+height+.3*base'],['-.5*base+.5*base','-1+height+.3*base']],'gold'),s('heightGuide',['-base/2','-1'],['-base/2','-1+height'],'green'),rect('layer','2','-1','base','base','green')],readouts:[ro('bottomArea','底面积','base^2'),ro('heightValue','高','height'),ro('volume','体积','base^2*height')],captions:['以正方形底面的直棱柱为例。','每个与底面平行的截面面积为 a²；沿垂直方向堆叠高度 h。','增大高度，体积与 h 成正比。','比较底面积和高；侧棱斜长不能代替垂直高。','一般柱体公式是底面积乘垂直高。'],formula:String.raw`V=Sh\quad(\text{柱体})`,intro:['front','top'],focus:['front','top','heightGuide','layer'],animate:['height',1.5,2.3]});
add({index:19,id:'geometry-pyramid-volume',renderer:'geometry',parameters:{base:p('底边 a',.8,2,1.5),height:p('锥高 h',.5,2.5,1.5)},objects:[rect('comparison','1','-1','base','height','muted'),poly('triangle',[['-2','-1'],['-2+base','-1'],['-2+base/2','-1+height']],'gold'),s('altitude',['-2+base/2','-1'],['-2+base/2','-1+height'],'green',true),rect('bottom','-2','-1.5','base','.35','green')],readouts:[ro('baseArea','底面积','base^2'),ro('prismVolume','同底等高柱体体积','base^2*height'),ro('coneVolume','锥体体积','base^2*height/3')],captions:['同底等高的柱体作为对照。','锥体在高度 z 的平行截面积随 z 缩小；体积是柱体的三分之一。','改变锥高，柱与锥的体积同时线性变化。','三角形只是轴截面；二维面积比不能直接当作三维体积证明。','一般锥体满足 V=Sh/3，h 是底面到顶点的垂直距离。'],formula:String.raw`V_{\text{锥}}=\frac13Sh`,intro:['comparison','bottom'],focus:['comparison','triangle','altitude','bottom'],animate:['height',1.5,2.3]});
add({index:20,id:'geometry-sphere-measure',renderer:'geometry',parameters:{radius:p('球半径 r',.5,2,1)},objects:[circle('sphere',['0','0'],'radius'),circle('greatCircle',['0','0'],'radius','muted'),s('radius',['0','0'],['radius','0'],'gold'),rect('square','-radius','-radius','2*radius','2*radius','green')],readouts:[ro('area','球表面积','4*pi*radius^2'),ro('volume','球体积','4*pi*radius^3/3'),ro('ratio','V/S','radius/3')],captions:['圆只表示球的轴截面；球面本身是三维曲面。','半径 r 同时决定球表面积与体积。','半径翻倍时，表面积变为 4 倍，体积变为 8 倍。','调节 r 并比较 r² 与 r³ 的增长。','公式需要三维推导；截面图不能证明球面积或体积。'],formula:String.raw`S=4\pi r^2,\qquad V=\frac43\pi r^3`,intro:['sphere','radius'],focus:['sphere','radius','square'],animate:['radius',1,1.8]});

// 21–38: spatial position, incidence, parallelism and orthogonality.
add({index:21,id:'geometry-line-plane-positions',renderer:'solid',parameters:{height:p('直线高度 h',-1,1,.8),tilt:p('法向倾斜 t',-.6,.6,0)},objects:[P('alpha','平面 α'),L('a','直线 a',['0','height','0'],['1','tilt','0'],'gold')],readouts:[ro('h','直线高度','height'),ro('t','方向法向分量','tilt')],captions:['平面 α 的法向是竖直方向。','a 在面内、与面平行或与面相交，由高度和方向共同决定。','改变倾斜量，让原本平行的直线与面相交。','t=0 且 h=0 为面内；t=0 且 h≠0 为平行；t≠0 为相交。','画面有限；即使交点不在画面内，延长直线仍与平面相交。'],formula:String.raw`t=0,h=0:\ a\subset\alpha;\quad t=0,h\ne0:\ a\parallel\alpha`,intro:['alpha'],focus:['alpha','a'],animate:['tilt',0,.5]});
add({index:22,id:'geometry-two-line-positions',renderer:'solid',parameters:{height:p('第二直线高度',0,2,1),angle:p('方向角',0,1.3,.7)},objects:[L('a','a',['0','0','0'],['1','0','0']),L('b','b',['0','height','0'],['cos(angle)','0','sin(angle)'],'gold'),Q('origin','交点候选',['0','0','0'],'green')],readouts:[ro('h','层间高度','height'),ro('direction','方向角（度）','angle*180/pi')],captions:['固定 a，令 b 从另一高度经过。','高度不为零且方向不平行时，两直线异面。','降低 b：高度为零时，二线在原点相交。','若保持高度非零并令方向角为零，可得到平行；相交、平行、异面由两个条件区分。','图中视觉投影的交叉不等于真实相交。'],formula:String.raw`\text{空间两直线：相交、平行或异面}`,intro:['a'],focus:['a','b','origin'],animate:['height',1,0]});
add({index:23,id:'geometry-skew-lines',renderer:'solid',parameters:{height:p('异面偏移 h',0,2,1)},objects:[L('a','a',['0','0','0'],['1','0','0']),L('b','b',['0','height','0'],['0','0','1'],'gold'),S('shortest',['0','0','0'],['0','height','0'],'green'),P('alpha','含 a 的平面')],readouts:[ro('distance','两线最短距离（本例）','height')],captions:['a 沿 x 轴，b 沿 z 轴但处于不同高度。','高度 h>0 时，不相交且方向不平行，因此异面。','让 h 减到 0，直线在原点相交；异面条件消失。','旋转视角比较投影交叉与空间实际距离。','本例中最短公垂线为绿色线段；异面不是“看起来没有交点”。'],formula:String.raw`h>0\Rightarrow a,b\text{ 异面};\qquad h=0\Rightarrow a\cap b\ne\varnothing`,intro:['a','b'],focus:['a','b','shortest','alpha'],animate:['height',1,0]});
add({index:25,id:'geometry-line-plane-parallel-property',renderer:'solid',parameters:{height:p('线面距离 h',.4,2,1)},objects:[P('alpha','平面 α'),P('beta','过 a 的截面 β',['0','0','0'],['1','0','0'],['0','1','0'],'green'),L('a','a',['0','height','0'],['1','0','0'],'gold'),L('seam','α∩β',['0','0','0'],['1','0','0'],'green'),S('distance',['0','0','0'],['0','height','0'])],readouts:[ro('h','线面距离','height')],captions:['先固定与 α 平行的直线 a。','过 a 作另一平面 β，β 与 α 交于一条直线。','调整 a 的高度，交线方向始终与 a 一致。','确保 β 真包含 a；任意交面不能推出该性质。','当 a∥α 且 a⊂β、α∩β=b 时，a∥b。'],formula:String.raw`a\parallel\alpha,\ a\subset\beta,\ \alpha\cap\beta=b\Rightarrow a\parallel b`,intro:['alpha','a'],focus:['alpha','beta','a','seam'],animate:['height',1,1.8]});
add({index:27,id:'geometry-parallel-plane-property',renderer:'solid',parameters:{height:p('平行面间距 h',.5,2,1)},objects:[P('alpha','α'),P('beta','β',['0','height','0'],['1','0','0'],['0','0','1'],'green'),P('gamma','截面 γ',['0','0','0'],['1','0','0'],['0','1','0']),L('a','α∩γ',['0','0','0'],['1','0','0'],'gold'),L('b','β∩γ',['0','height','0'],['1','0','0'],'gold')],readouts:[ro('h','两平面间距','height')],captions:['α 与 β 互相平行。','γ 同时截两平面，留下交线 a、b。','改变两平面间距，交线位置变但方向不变。','旋转视角可验证投影角变化不影响平行性。','要求两条交线实际存在；平行平面被同一平面所截，交线平行。'],formula:String.raw`\alpha\parallel\beta,\ \alpha\cap\gamma=a,\ \beta\cap\gamma=b\Rightarrow a\parallel b`,intro:['alpha','beta'],focus:['alpha','beta','gamma','a','b'],animate:['height',1,1.8]});
add({index:28,id:'geometry-parallel-plane-distance',renderer:'solid',parameters:{height:p('平行面间距 h',.4,2.3,1.2),offset:p('垂线足水平位置 x',-1,1,0)},objects:[P('alpha','α'),P('beta','β',['0','height','0'],['1','0','0'],['0','0','1'],'green'),S('normal',['offset','0','0'],['offset','height','0'],'gold'),S('slanted',['offset','0','0'],['offset+1','height','0'],'muted'),Q('foot','垂足',['offset','0','0'])],readouts:[ro('distance','公垂线段长','height'),ro('oblique','斜线段长','sqrt(height^2+1)')],captions:['两平行平面的法向距离处处相同。','黄色公垂线段给出最短距离；灰色斜线段较长。','改变平面间距，两段长度同步变化但大小不同。','移动垂足 x，不改变两平面的距离。','平面距离取公垂线段长度，不能取任意斜连线。'],formula:String.raw`d(\alpha,\beta)=|PQ|\quad(PQ\perp\alpha,\ PQ\perp\beta)`,intro:['alpha','beta'],focus:['alpha','beta','normal','slanted','foot'],animate:['height',1.2,2]});
add({index:30,id:'geometry-two-line-perpendicular',renderer:'solid',parameters:{angle:p('方向夹角 θ',.2,2.5,1.57),height:p('两线错层 h',0,1.2,0)},objects:[L('a','a',['0','0','0'],['1','0','0']),L('b','b',['0','height','0'],['cos(angle)','0','sin(angle)'],'gold'),S('gap',['0','0','0'],['0','height','0'],'green')],readouts:[ro('degrees','方向夹角（度）','angle*180/pi'),ro('dot','方向向量点积','cos(angle)')],captions:['空间直线可相交，也可异面。','垂直判断看方向夹角，不要求实际相交。','改变方向夹角，点积在 90° 时为 0。','改变错层高度：异面时仍可垂直。','两方向向量点积为零是垂直判据；画面投影直角不可靠。'],formula:String.raw`\vec u\cdot\vec v=0\iff a\perp b`,intro:['a','b'],focus:['a','b','gap'],animate:['angle',.7,Math.PI/2]});
add({index:31,id:'geometry-line-plane-perpendicular',renderer:'solid',parameters:{tilt:p('偏离法向的倾角 θ',0,1.1,.6)},objects:[P('alpha','α'),L('normal','法线 n',['0','0','0'],['0','1','0'],'muted'),L('a','直线 a',['0','0','0'],['sin(tilt)','cos(tilt)','0'],'gold'),L('x','面内 x 方向',['0','0','0'],['1','0','0'],'green'),L('z','面内 z 方向',['0','0','0'],['0','0','1'],'green')],readouts:[ro('angle','偏离垂直的角度','tilt*180/pi'),ro('inner','a 与面内 x 向量的点积','sin(tilt)')],captions:['平面 α 内存在无数条不同方向的直线。','a 沿平面法向时，与面内每个方向都垂直。','倾斜 a，它与 x 方向的点积不再为零。','θ=0 是垂直；仅与 z 方向垂直不足以判定线面垂直。','线面垂直属于方向关系，不靠屏幕上的直角判断。'],formula:String.raw`a\perp\alpha\iff a\perp b\ (\forall b\subset\alpha)`,intro:['alpha','normal'],focus:['alpha','normal','a','x','z'],animate:['tilt',.6,0]});
add({index:33,id:'geometry-line-plane-perpendicular-property',renderer:'solid',parameters:{tilt:p('第二直线偏离法向 θ',0,1.1,.5)},objects:[P('alpha','α'),L('a','a',['-1','0','0'],['0','1','0'],'gold'),L('b','b',['1','0','0'],['sin(tilt)','cos(tilt)','0'],'green'),S('base',['-1','0','0'],['1','0','0'])],readouts:[ro('directionDot','单位方向点积','cos(tilt)')],captions:['a 垂直于 α，方向沿其法向。','若 b 也垂直于 α，两条直线的方向同向或反向。','让 b 倾斜，垂直条件消失，a 与 b 不再平行。','θ=0 时两条直线虽不重合却平行。','同垂直于一个平面的两条直线平行。'],formula:String.raw`a\perp\alpha,\ b\perp\alpha\Rightarrow a\parallel b`,intro:['alpha','a'],focus:['alpha','a','b','base'],animate:['tilt',.5,0]});
add({index:34,id:'geometry-perpendicular-planes',renderer:'solid',parameters:{angle:p('二面角 θ',.3,2.5,1)},objects:[P('alpha','α'),P('beta','β',['0','0','0'],['cos(angle)','sin(angle)','0'],['0','0','1'],'green'),L('hinge','公共棱',['0','0','0'],['0','0','1'],'gold'),S('rayA',['0','0','0'],['1.5','0','0']),S('rayB',['0','0','0'],['1.5*cos(angle)','1.5*sin(angle)','0'])],readouts:[ro('degrees','二面角（度）','angle*180/pi'),ro('cosine','两截面射线点积','cos(angle)')],captions:['两平面沿公共棱相交。','在同一棱上点作两条垂棱射线，夹角代表二面角。','旋转 β 到 90°，截面射线点积为零。','试试非直角，此时即使画面看来垂直也不满足定义。','直二面角是面面垂直的定义。'],formula:String.raw`\alpha\perp\beta\iff\text{二面角}=90^\circ`,intro:['alpha','beta','hinge'],focus:['alpha','beta','hinge','rayA','rayB'],animate:['angle',1,Math.PI/2]});
add({index:35,id:'geometry-perpendicular-planes-criterion',renderer:'solid',parameters:{tilt:p('面内直线偏离法向 θ',0,1.2,.6)},objects:[P('alpha','α'),P('beta','β',['0','0','0'],['sin(tilt)','cos(tilt)','0'],['0','0','1'],'green'),L('normal','α 的法线',['0','0','0'],['0','1','0'],'gold'),L('inside','β 内直线',['0','0','0'],['sin(tilt)','cos(tilt)','0'],'green'),L('hinge','交线',['0','0','0'],['0','0','1'])],readouts:[ro('deviation','β 内直线偏离法线（度）','tilt*180/pi')],captions:['先给出 α 的一条垂线。','β 若包含这条垂线，则沿交线张成的 β 与 α 垂直。','让 β 内的指定直线偏离法线，判定条件消失。','把 θ 调回零，对比直线是否真正位于 β。','须同时满足直线垂直于 α 且包含在 β 内。'],formula:String.raw`l\perp\alpha,\ l\subset\beta\Rightarrow\alpha\perp\beta`,intro:['alpha','normal'],focus:['alpha','beta','normal','inside','hinge'],animate:['tilt',.6,0]});
add({index:36,id:'geometry-perpendicular-planes-property',renderer:'solid',parameters:{tilt:p('β 内线偏离交线垂角 θ',0,1.1,.5)},objects:[P('alpha','α'),P('beta','β',['0','0','0'],['0','1','0'],['0','0','1'],'green'),L('hinge','α∩β',['0','0','0'],['0','0','1'],'gold'),L('within','β 内直线',['0','0','0'],['0','cos(tilt)','sin(tilt)'],'green'),L('normal','α 法线',['0','0','0'],['0','1','0'],'muted')],readouts:[ro('dot','与交线方向点积','sin(tilt)'),ro('angle','偏离角（度）','tilt*180/pi')],captions:['α 与 β 垂直，交线沿 z 方向。','β 内经过交线点、并垂直交线的直线沿 y 方向。','倾斜 β 内直线，它不再垂直交线，也不再垂直 α。','θ=0 满足两条件；不能只凭“在 β 内”推出垂直 α。','面面垂直性质需要 β 内直线垂直于两面交线。'],formula:String.raw`\alpha\perp\beta,\ l=\alpha\cap\beta,\ a\subset\beta,\ a\perp l\Rightarrow a\perp\alpha`,intro:['alpha','beta','hinge'],focus:['alpha','beta','hinge','within','normal'],animate:['tilt',.5,0]});
add({index:38,id:'geometry-point-plane-distance',renderer:'solid',parameters:{height:p('点到平面的高度 h',.4,2.4,1.2),offset:p('斜点水平偏移 x',.2,1.5,.8)},objects:[P('alpha','平面 α'),Q('point','P',['0','height','0']),Q('foot','垂足 H',['0','0','0'],'green'),S('normal',['0','height','0'],['0','0','0'],'gold'),Q('other','面内点 Q',['offset','0','0']),S('oblique',['0','height','0'],['offset','0','0'],'muted')],readouts:[ro('distance','垂距 PH','height'),ro('longer','斜距 PQ','sqrt(height^2+offset^2)')],captions:['点 P 在平面 α 外。','从 P 作垂线，H 是垂足；另取平面内 Q 作斜线。','调整 P 的高度，PH 总是短于非垂直的 PQ。','移动 Q，斜距变化而点到平面的距离不变。','点到平面的距离是垂线段长度，不是任意连接线段。'],formula:String.raw`d(P,\alpha)=PH\leq PQ\quad(Q\in\alpha)`,intro:['alpha','point'],focus:['alpha','point','foot','normal','other','oblique'],animate:['height',1.2,2]});

// 39–50: coordinate equations and conic parameter relations.
add({index:39,id:'geometry-line-slope',renderer:'coordinate',parameters:{angle:p('倾斜角 α（弧度）',0,1.25,.45)},objects:[line('straight',['0','0'],['1','tan(angle)']),s('run',['-1','-1*tan(angle)'],['1','-1*tan(angle)'],'green'),s('rise',['1','-1*tan(angle)'],['1','tan(angle)'],'gold'),pt('A','A',['-1','-1*tan(angle)']),pt('B','B',['1','tan(angle)'])],readouts:[ro('riseValue','纵向增量 Δy','2*tan(angle)'),ro('slopeValue','斜率 k','tan(angle)')],captions:['在直线上取横坐标差为 2 的 A、B。','比较 Δy 与 Δx，斜率等于纵向增量除以横向增量。','增大倾斜角，斜率随 tanα 增大。','本场景只显示 0° 至约 72°；90° 时 tan 无定义，竖直线斜率不存在。','斜率与任意两不同点的差商一致；钝角时斜率为负。'],formula:String.raw`k=\frac{y_2-y_1}{x_2-x_1}=\tan\alpha\quad(x_1\ne x_2)`,intro:['straight','A','B'],focus:['straight','A','B','run','rise'],animate:['angle',.45,1.1]});
add({index:40,id:'geometry-point-slope-equation',renderer:'coordinate',parameters:{slope:p('斜率 k',-1.8,1.8,.7),x0:p('已知点横坐标 x₀',-1.5,1.5,-.8),y0:p('已知点纵坐标 y₀',-1.5,1.5,.4)},objects:[line('straight',['x0','y0'],['1','slope']),pt('P','P(x₀,y₀)',['x0','y0']),pt('Q','Q',['x0+1','y0+slope'],'green'),s('run',['x0','y0'],['x0+1','y0'],'green'),s('rise',['x0+1','y0'],['x0+1','y0+slope'],'gold')],readouts:[ro('k','斜率','slope'),ro('value','Q 的纵坐标','y0+slope')],captions:['固定一点 P(x₀,y₀) 和斜率 k。','沿 x 增加 1，沿 y 增加 k，得到另一点 Q。','调节 k，直线绕 P 旋转且始终经过 P。','移动 P，再核对它代入方程必成立。','点斜式只表示有有限斜率的非竖直直线。'],formula:String.raw`y-y_0=k(x-x_0)`,intro:['P'],focus:['P','Q','straight','run','rise'],animate:['slope',.7,-1.2]});
add({index:41,id:'geometry-line-equation-forms',renderer:'coordinate',parameters:{slope:p('斜率 k',-1.6,1.6,.8),intercept:p('纵截距 b',-1.4,1.4,.5)},objects:[line('straight',['0','intercept'],['1','slope']),pt('Y','(0,b)',['0','intercept']),pt('A','A',['-1','intercept-slope'],'gold'),pt('B','B',['1','intercept+slope'],'green'),line('vertical',['2','0'],['0','1'],'muted')],readouts:[ro('k','有限斜率','slope'),ro('b','纵截距','intercept'),ro('C','一般式常数 C','-intercept')],captions:['以一条非竖直直线和两点 A、B 为例。','点斜式、斜截式与一般式可描述同一条直线。','改变纵截距，三种非竖直写法同步平移。','灰色竖直线 x=2 不能写成 y=kx+b，但可写成一般式。','两点式要求两点横坐标不同；一般式 Ax+By+C=0 要求 A、B 不同时为零。'],formula:String.raw`y=kx+b\iff kx-y+b=0;\qquad x=2\iff x-2=0`,intro:['straight','Y'],focus:['straight','Y','A','B','vertical'],animate:['intercept',.5,-1]});
add({index:42,id:'geometry-point-line-distance',renderer:'coordinate',parameters:{px:p('点 P 的横坐标',-2,2,1),py:p('点 P 的纵坐标',-1,2,1)},objects:[line('straight',['0','1'],['1','-.5']),pt('P','P',['px','py']),pt('H','垂足 H',['px-(px+2*py-2)/5','py-2*(px+2*py-2)/5'],'green'),s('normal',['px','py'],['px-(px+2*py-2)/5','py-2*(px+2*py-2)/5'],'gold'),s('oblique',['px','py'],['px+1','(1-.5*(px+1))'],'muted')],readouts:[ro('numerator','|Ax₀+By₀+C|','abs(px+2*py-2)'),ro('distance','点线距离','abs(px+2*py-2)/sqrt(5)')],captions:['直线选用 x+2y−2=0，点 P 可移动。','垂足 H 给出 P 到直线的最短线段。','移动 P，垂足随 P 的正交投影同步移动。','P 落到直线上时距离为 0；斜连线不能作距离。','分母 √(A²+B²) 对法向量长度归一化。'],formula:String.raw`d=\frac{|Ax_0+By_0+C|}{\sqrt{A^2+B^2}}`,intro:['straight','P'],focus:['straight','P','H','normal','oblique'],animate:['py',1,-.5]});
add({index:44,id:'geometry-circle-general-equation',renderer:'coordinate',parameters:{centerX:p('圆心横坐标 a',-1.5,1.5,.5),centerY:p('圆心纵坐标 b',-1.5,1.5,-.4),radius:p('半径 r',.5,2,1.2)},objects:[circle('round',['centerX','centerY'],'radius'),pt('center','圆心',['centerX','centerY'],'green'),pt('edge','圆上一点',['centerX+radius','centerY'])],readouts:[ro('D','一次项系数 D','-2*centerX'),ro('E','一次项系数 E','-2*centerY'),ro('F','常数 F','centerX^2+centerY^2-radius^2'),ro('radiusSquared','判别量 D²+E²−4F','4*radius^2')],captions:['从圆心 (a,b) 与半径 r 的标准式出发。','展开平方得到 x²+y²+Dx+Ey+F=0。','移动圆心或改变半径，系数 D、E、F 联动。','D²+E²−4F>0 表示非退化实圆；等于 0 为单点，小于 0 无实点。','一般式必须二次项同系数、无 xy 项，并满足半径平方为正。'],formula:String.raw`D=-2a,\ E=-2b,\ F=a^2+b^2-r^2`,intro:['center','round'],focus:['center','round','edge'],animate:['radius',1.2,1.8]});
add({index:46,id:'geometry-ellipse-eccentricity',renderer:'coordinate',parameters:{major:p('长半轴 a',2.4,3.6,3),minor:p('短半轴 b',.6,2,1.5)},objects:[curve('ellipse','major*cos(x)','minor*sin(x)',[0,2*Math.PI]),pt('F1','F₁',['-sqrt(major^2-minor^2)','0'],'gold'),pt('F2','F₂',['sqrt(major^2-minor^2)','0'],'gold'),s('majorAxis',['-major','0'],['major','0'],'muted'),s('minorAxis',['0','-minor'],['0','minor'],'green')],readouts:[ro('c','焦半距 c','sqrt(major^2-minor^2)'),ro('e','离心率 e','sqrt(major^2-minor^2)/major')],captions:['固定长半轴 a 与短半轴 b，且 a>b>0。','由 c²=a²−b² 确定左右焦点位置。','改变短半轴，焦距及形状同时变化。','b 越小，e 越接近 1；b 越接近 a，e 越接近 0。','非退化且两焦点不同的椭圆满足 0<e<1。'],formula:String.raw`c^2=a^2-b^2,\qquad e=\frac ca\in(0,1)`,intro:['ellipse','majorAxis'],focus:['ellipse','majorAxis','minorAxis','F1','F2'],animate:['minor',1.5,.7]});
add({index:48,id:'geometry-hyperbola-asymptotes',renderer:'coordinate',parameters:{real:p('实半轴 a',1,2,1.4),imag:p('虚半轴 b',.5,1.5,.9)},objects:[curve('right','real*sqrt(1+x^2)','imag*x',[-2,2]),curve('left','-real*sqrt(1+x^2)','imag*x',[-2,2],'green'),line('asymPlus',['0','0'],['real','imag'],'gold'),line('asymMinus',['0','0'],['real','-imag'],'gold'),pt('F1','F₁',['-sqrt(real^2+imag^2)','0']),pt('F2','F₂',['sqrt(real^2+imag^2)','0'])],readouts:[ro('slope','渐近线斜率绝对值','imag/real'),ro('e','离心率','sqrt(real^2+imag^2)/real')],captions:['两支双曲线对应 x²/a²−y²/b²=1。','渐近线为 y=±(b/a)x，焦点在 x 轴。','改变 b，渐近线斜率与焦点位置同时变化。','双曲线向渐近线靠近，但不与其相交；e>1。','这里 a、b 均为正数，c²=a²+b²；不把渐近线当双曲线的分支。'],formula:String.raw`y=\pm\frac ba x,\quad c^2=a^2+b^2,\quad e=\frac ca>1`,intro:['right','left'],focus:['right','left','asymPlus','asymMinus','F1','F2'],animate:['imag',.9,1.4]});
add({index:50,id:'geometry-conic-equation-research',renderer:'coordinate',parameters:{scale:p('尺度参数 a',1,2,1.4)},objects:[curve('ellipseCase','-5+scale*cos(x)','0.65*scale*sin(x)',[0,2*Math.PI]),curve('hyperbolaRight','scale*sqrt(1+x^2)','0.65*scale*x',[-1.3,1.3],'gold'),curve('hyperbolaLeft','-scale*sqrt(1+x^2)','0.65*scale*x',[-1.3,1.3],'gold'),curve('parabolaCase','5+x^2/(2*scale)','x',[-1.8,1.8],'green'),pt('ellipseCenter','E',['-5','0'],'muted'),pt('hyperbolaCenter','H',['0','0'],'muted'),pt('parabolaVertex','P',['5','0'],'muted')],readouts:[ro('a','共用尺度参数','scale'),ro('ellipseFocus','椭圆焦半距','scale*sqrt(1-.65^2)'),ro('hyperbolaFocus','双曲线焦半距','scale*sqrt(1+.65^2)')],captions:['三个局部坐标原点依次位于 x=−5、0、5，避免曲线互相遮挡。','椭圆闭合，双曲线有两支，抛物线是一条开曲线。','改变尺度只做相似伸缩，不改变这些实例的类型。','检查每条曲线的局部方程；这是典型例子，不是全部一般二次方程分类。','令 X 为相对各自局部原点的横坐标。完整分类还需考虑 xy 项、坐标变换与退化情形。'],formula:String.raw`\frac{X^2}{a^2}+\frac{y^2}{b^2}=1,\quad\frac{X^2}{a^2}-\frac{y^2}{b^2}=1,\quad y^2=2pX`,intro:['ellipseCase','ellipseCenter'],focus:['ellipseCase','hyperbolaRight','hyperbolaLeft','parabolaCase','ellipseCenter','hyperbolaCenter','parabolaVertex'],animate:['scale',1.4,1.9],xRange:[-8,9]});

export const geometryCompletionScenes=scenes.map(make);
